$(document).ready(function() {

	//jQuery event for Enter key press - plugin
	$.fn.pressEnter = function(fn) {  
		return this.each(function() {  
			$(this).bind('enterPress', fn);
			$(this).keyup(function(e){
				if(e.keyCode == 13)
				{
				  $(this).trigger("enterPress");
				}
			})
		});  
	 };


	//PNR History- GET PNR Status
	$(".getpnrstatus").click(function() {
		if(currentTimeCheck()){
		}else{
			return false;
		}
		var current = $(this);
		var pnrnum = $(this).attr('name');
		pnrnum = pnrnum.match(/[0-9]+/);
		$('#displaypnrstatus').html("<h3><i class=\"icon-refresh icon-spin\"></i> Retrieving PNR Status...</h3>");

		$.ajax({
			type: "POST",
			url: "../userscripts/getpnrstatus.php",
			data: "pnrNum="+pnrnum,
			success: function(html){
				var newhtml = html+'<br><a id="getSMS" class="getsms btn btn-warning" name="getSMS" rel="tooltip" title="Get Message to your registered Mobile">Get SMS</a>&nbsp;&nbsp;<a data-toggle="modal" href="#mySMSModal" rel="tooltip" title="Send Message to any Mobile" id="sendSMS" class="sendsms btn btn-info" name="sendSMS" value="">Send SMS</a>';
				$('#displaypnrstatus').html(html);
				dataLayer.push({'event': 'pnrstatus_pnrhistory'});
				//_gaq.push(['_trackEvent','PNR Status','pnrhistory']);
			}
		});
	});

	//Get PNR Status on PNR Status page
	function getPnrStatus(){
		if(currentTimeCheck()){
		}else{
			return false;
		}
		var current = $(this);
		var pnrnum = $('#displaypnrstatusinput').val();
		if($.isNumeric(pnrnum)){
		}else{
			alert("Enter a Numberic Value");
			return false;
		}
		if(pnrnum==pnrnum.match(/[0-9]{10}/)){
		}else{
			alert("Enter 10 Digit PNR Number");
			return false;
		}
		$('#displaypnrstatus').html("<h3><i class=\"icon-refresh icon-spin\"></i> Retrieving PNR Status...</h3>");

		$.ajax({
			type: "POST",
			url: "../userscripts/getpnrstatus.php",
			data: "pnrNum="+pnrnum,
			success: function(html){
				var newhtml = html+'<br><a id="getSMS" class="getsms btn btn-warning" name="getSMS" rel="tooltip" title="Get Message to your registered Mobile">Get SMS</a>&nbsp;&nbsp;&nbsp;<a data-toggle="modal" href="#mySMSModal" rel="tooltip" title="Send Message to any Mobile" id="sendSMS" class="sendsms btn btn-info" name="sendSMS" value="">Send SMS</a>';
				$('#displaypnrstatus').html(html);
				dataLayer.push({'event': 'pnrstatus_pnrstatus'});
				//_gaq.push(['_trackEvent','PNR Status','pnrstatus']);
			}
		});
	}

	$('input[name="displaypnrstatusinput"]').pressEnter(function(){ getPnrStatus(); });
	$("#displaypnrstatusinputgetstatus").click(function() { getPnrStatus(); });

	//PNR History - Sending SMS to Registered Mobile
	$(".getsms").click(function() {
		if(checkLinkedAccount()){
		}else{
			window.location.href = "../user/profile";
			return false;
		}
		if(currentTimeCheck()){
		}else{
			return false;
		}
		var current = $(this);
		//check whether the button is enabled or not
		if(current.attr('class')=="sendsms btn btn-inverse disabled"){
			return false;
		}
		//window for confirmation
		var conf = confirm("Do you want to get SMS to your registered Mobile?");
		if(conf==true){
		}else{
			return false;
		}
		var pnrnum = $(this).attr('name');
		pnrnum = pnrnum.match(/[0-9]+/);
		current.html("<i class=\"icon-refresh icon-spin\"></i> Sending.");
		//alert("You are going to send the SMS for "+ pnrnum);

		$.ajax({
			type: "POST",
			url: "../userscripts/sendtextmessage.php",
			data: "pnrNum="+pnrnum+"&regMobile=Y" ,
			success: function(html){
				if(html=="Success"){
					current.html("<i class=\"icon-ok\"></i> "+html);
					current.attr('class','sendsms btn btn-inverse disabled');
					dataLayer.push({'event': 'getsms_success'});
					//_gaq.push(['_trackEvent','Get SMS','Success']);
				}else if(html=="Failure"){
					current.html("<i class=\"icon-warning-sign\"></i> "+html);
					dataLayer.push({'event': 'getsms_failure'});
					//_gaq.push(['_trackEvent','Get SMS','Failure']);
				}else{
					current.html("Try later");
				}
			}
		});
	});

	//PNR History - Sending SMS to Any Mobile
	$(document).on("click",'.sendsms',function(){ //Toggle the send SMS button on modal
		var current = $(this);
		$('#currentpnr').val(current.attr('value'));
		$('.sendsmsanymobile').html("Send SMS");
		$('.sendsmsanymobile').attr('class','sendsmsanymobile btn btn-info');
	});

	$('.sendsms').click(function(){ $('#currentmobileNum').focus(); });

	function sendsmsAnyMobile(current){
		if(checkLinkedAccount()){
		}else{
			window.location.href = "../user/profile";
			return false;
		}
		if(currentTimeCheck()){
		}else{
			return false;
		}
		
		//If the Send SMS button is disabled stop the action
		if(current.attr('class')=="sendsmsanymobile btn btn-info disabled"){
			return false;
		}
		//if mobile number is empty stop the action
		var anymobilenum = $('#currentmobileNum').val();
		if(anymobilenum){ 
		}else{
			return false;
		}	
		var pnrnum = $('#currentpnr').val();
		current.html("<i class=\"icon-refresh icon-spin\"></i> Sending.");
		//window for confirmation
		var conf = confirm("Do you want to send the SMS?");
		if(conf==true){
		}else{
			return false;
		}

		$.ajax({
			type: "POST",
			url: "../userscripts/sendtextmessage.php",
			data: "pnrNum="+pnrnum+"&mobileNum="+anymobilenum+"&anyMobile=Y" ,
			success: function(html){
				if(html=="Success"){
					current.html("<i class=\"icon-ok\"></i> "+html);
					current.attr('class','sendsmsanymobile btn btn-info disabled');
					dataLayer.push({'event': 'sendsms_success'});
					//_gaq.push(['_trackEvent','Send SMS','Success']);
					//current.attr('disabled','disabled');
				}else if(html=="Failure"){
					current.html("<i class=\"icon-warning-sign\"></i> "+html);
					current.attr('class','sendsmsanymobile btn btn-info disabled');
					dataLayer.push({'event': 'sendsms_failure'});
					//_gaq.push(['_trackEvent','Send SMS','Failure']);
				}else{
					dataLayer.push({'event': 'sendsms_failure'});
					current.html("Try Again!");
				}
			}
		});
	}
	$(".sendsmsanymobile").click(function() { var current = $(this); sendsmsAnyMobile(current); });
	$('#currentmobileNum').pressEnter(function(){ var current = $('.sendsmsanymobile'); sendsmsAnyMobile(current); });

	//User Profile - Change mobile number - Toggle
	$("#changeprofilemob").on("click",function() {
		$('#formprofilemob').show();
		$('#profilemob').hide();
	});
	$("#cancelprofilemob").on("click",function() {
		$('#formprofilemob').hide();
		$('#profilemob').show();
	});

	//User Profile - Password Toggle
	$("#changeprofilepwd").on("click",function() {
		$('#formprofilepwd').show();
		$('#profilepwd').hide();
	});
	$("#cancelprofilepwd").on("click",function() {
		$('#formprofilepwd').hide();
		$('#profilepwd').show();
	});

	//Sync with IRCTC
	function syncIrctc(){
		var current = $(this);
		var irctcusername = $('#irctcusername').val();
		var irctcpassword = $('#irctcpassword').val();
		if(irctcusername){}else{alert("Enter Username");return false;}
		if(irctcpassword){}else{alert("Enter Password");return false;}

		$('#displayirctcimportstatus').html("<h5><i class=\"icon-refresh icon-spin\"></i> Importing PNR History from your IRCTC account...</h5>");
		//current.html("<i class=\"icon-refresh icon-spin\"></i> Importing...");
		$.ajax({
			type: "POST",
			url: "../userscripts/irctcpnrhistoryimport.php",
			data: "irctcUsername="+irctcusername+"&irctcPassword="+irctcpassword+"&savePnrHistory=Y" ,
			success: function(html){
				var result = html;
				if(result=="Success"){
					$('#displayirctcimportstatus').html("<h5>Successfully Imported your booking history!</h5>");
					$(function() {
						setTimeout(function() {
							location.reload();
						}, 2000);
					});
					//current.html("<i class=\"icon-thumbs-up\"></i> Success");
				} else if(result=="Failure"){
					$('#displayirctcimportstatus').html("<h5>Your Booking history has been imported and upto date!!</h5>");
					$(function() {
						setTimeout(function() {
							location.reload();
						}, 2000);
					});
					//current.html("<i class=\"icon-warning-sign\"></i> Enough");
				} else if(result=="WrongPassword"){
					$('#displayirctcimportstatus').html("<h5>Wrong Username or Password! Please Try Again!</h5>");
				}else {
					$('#displayirctcimportstatus').html("<h5>There is a problem connecting to IRCTC Servers. Please try again!</h5>");
					//current.html("<i class=\"icon-warning-sign\"></i> Try Again");
				} 			
			}
		});
	}
	$("#importirctchistory").click(function() { syncIrctc(); });
	$('#irctcusername').pressEnter(function() { syncIrctc(); });
	$('#irctcpassword').pressEnter(function() { syncIrctc(); });

	//Search Trains between stations
	var stationname = ["AMB ANDAURA (AADR)","AMLAI (AAL)","ANGADIPPURAM (AAM)","ARALVAYMOZHI (AAY)","AMBUR (AB)","AMBLI ROAD (ABD)","AMBARI FALAKATA (ABFC)","AMBATURAI (ABI)","AMBIKA KALNA (ABKA)","AMBIKAPUR (ABKP)","AMBALE (ABLE)","AKBARPUR (ABP)","ABU ROAD (ABR)","ABOHAR (ABS)","AMBASA (ABSA)","A N DEV NAGAR (ACND)","ADONI (AD)","ADILABAD (ADB)","ADINA (ADF)","ANDHERI (ADH)","AHMEDABAD JN (ADI)","MANDI ADAMPUR (ADR)","ADRA JN (ADRA)","ADUTURAI (ADT)","ADHARTAL (ADTL)","ADITYAPUR (ADTP)","ADAVALI (ADVI)","AGRA FORT (AF)","ANGAMALI (AFK)","ASAFPUR (AFR)","AGRA CANTT (AGC)","AMGURI (AGI)","AMGAON (AGN)","AMARGARH (AGR)","AGARTALA (AGTL)","AGORI KHAS (AGY)","ACHHNERA JN (AH)","ABHAIPUR (AHA)","AHMADGARH (AHH)","ADIPUR (AI)","ALGAWAN (AIG)","AJMER JN (AII)","AIT (AIT)","ANJAR (AJE)","ANJHI SHAHABAD (AJI)","ARAKKONAM (AJJ)","AJNI (AJNI)","ARJUNI (AJU)","AKOLA JN (AK)","AKODIA (AKD)","AKANAPET (AKE)","AKBARGANJ (AKJ)","AKBARNAGAR (AKN)","AKALKOT ROAD (AKOR)","ANAKAPALLE (AKP)","AKALTARA (AKT)","ANKLESHWAR JN (AKV)","AKIVIDU (AKVD)","ATTILI (AL)","ALIA BADA (ALB)","ALLAHABAD JN (ALD)","ALER (ALER)","alai (ALJ)","ALIGARH JN (ALJN)","ALLEPPEY (ALLP)","ALAMPUR (ALMR)","ARIYALUR (ALU)","ALLAHABAD CITY (ALY)","AMBODALA (AMB)","AMETHI (AME)","ALAMNAGAR (AMG)","AZAMGARH (AMH)","AMRAVATI (AMI)","AMALSAD (AML)","AMLA JN (AMLA)","AHMADPUR JN (AMP)","AMBALAPUZHA (AMPA)","AMROHA (AMRO)","AMMASANDRA (AMSA)","AMALNER (AN)","ANAS (ANAS)","AMMANABROLU (ANB)","ADRSH NGR DELHI (ANDI)","ANAND NAGAR (ANDN)","ANANDAPURAM (ANF)","AHMADNAGAR (ANG)","ANGUL (ANGL)","ANKORAH AKORHA (ANH)","ANKAI (ANK)","ANKOLA (ANKL)","ANAND JN (ANND)","ANPARA (ANPR)","ANARA (ANR)","ANANDPUR SAHIB (ANSB)","ANTU (ANTU)","ANNAVARAM (ANV)","ANAND VIHAR (ANVR)","ANAND VIHAR TRM (ANVT)","ARUMUGANERI (ANY)","AONLA (AO)","AMONI (AONI)","ALIPUR DUAR JN (APDJ)","AYODHYAPATTANAM (APN)","ANUPPUR JN (APR)","ANAPARTI (APT)","ASHAPURA GOMAT (AQG)","ARA (ARA)","ARUNACHAL (ARCL)","AMARDA ROAD (ARD)","ARIGADA (ARGD)","AUNRIHAR JN (ARJ)","ARARIYA COURT (ARQ)","ARNI ROAD (ARV)","AHRAURA ROAD (ARW)","ASIFABAD ROAD (ASAF)","AISHBAGH (ASH)","ARSIKERE JN (ASK)","ASHOK NAGAR (ASKN)","ASANSOL JN (ASN)","AMRITSAR JN (ASR)","ASAOTI (AST)","ASARVA JN (ASV)","ATARRA (ATE)","ANTAH (ATH)","ATHMAL GOLA (ATL)","AITHAL (ATMO)","AWATARNAGAR (ATNR)","ANANTAPUR (ATP)","ATTABIRA (ATS)","ATARI (ATT)","ATTUR (ATU)","ALUABARI ROAD (AUB)","ANUGRAHA N ROAD (AUBR)","AUNG (AUNG)","AVADI (AVD)","ANAVARDIKHANPET (AVN)","ARAVALI ROAD (AVRD)","AURANGABAD (AWB)","ALWAR (AWR)","ALUVA (AWY)","AYODHYA (AY)","AKSHAYWAT R NGR (AYRN)","AZIMGANJ JN (AZ)","AZAMNAGAR ROAD (AZR)","BABINA (BAB)","BARAGOPAL (BAGL)","BASSI (BAI)","BANKA (BAKA)","BUDALUR (BAL)","BALUGAN (BALU)","BRAHMAPUR (BAM)","BANASWADI (BAND)","BASNI (BANE)","BANI (BANI)","BANO (BANO)","BANMOR (BAO)","BELAPUR (BAP)","GANJ BASODA (BAQ)","BARH (BARH)","BARAL (BARL)","BATALA JN (BAT)","BURHANPUR (BAU)","BELLARY JN (BAY)","BARAN (BAZ)","BABRALA (BBA)","BARUA BAMUNGAON (BBGN)","BARABANKI JN (BBK)","BARABHUM (BBM)","BARI BRAHMAN (BBMN)","BARABIL (BBN)","BHUBANESWAR (BBS)","BARBATPUR (BBTR)","BHABUA ROAD (BBU)","BAREILLY CITY (BC)","BACHWARA JN (BCA)","BERCHHA (BCH)","BACHHRAWAN (BCN)","BHACHAU BG (BCOB)","BARCHI ROAD (BCRD)","MUMBAI CENTRAL (BCT)","BHUCHCHU (BCU)","VARANASI CITY (BCY)","BADNERA JN (BD)","BANDEL JN (BDC)","BHADRACHALAM RD (BDCR)","BADODAR (BDDR)","BHEDIA (BDH)","BUDHI (BDHY)","VADAKARA (BDJ)","VINDHYACHAL (BDL)","BADAMI (BDM)","BHADAN (BDN)","BANDRA TERMINUS (BDTS)","BADNAPUR (BDU)","BUDVEL (BDVL)","BHADRAVATI (BDVT)","BANDANWARA (BDW)","BODWAD (BDWD)","BIRADHWAL (BDWL)","BADARWAS (BDWS)","BUDDIREDDIPPATI (BDY)","BAREILLY (BE)","BIHIYA (BEA)","BEAS (BEAS)","BELDANGA (BEB)","BEHTAGOKUL (BEG)","BAGDIHI (BEH)","BEOHARI (BEHR)","BIHAR SHARIF (BEHS)","BELA (BELA)","BUDAUN (BEM)","BEAWAR (BER)","B CEMENT NAGAR (BEY)","BAGETAR (BF)","BORHAT (BFD)","BHORAS BUDRUKH (BFJ)","BHALUI (BFM)","BEKAL FORT (BFR)","BHONGIR (BG)","BAGBAHRA (BGBR)","BAGHAULI (BGH)","BAGALKOT (BGK)","BHAGAT KI KOTHI (BGKT)","BELGAUM (BGM)","BHAGALPUR (BGP)","BAGHUAPAL (BGPL)","BHONGAON (BGQ)","BEGU SARAI (BGS)","BISUGIRSHARIF (BGSF)","BAGRA TAWA (BGTA)","BAIGUDA (BGUA)","BHIGWAN (BGVN)","BANGRIPOSI (BGY)","BAHADURGARH (BGZ)","BHARUCH JN (BH)","BADLA GHAT (BHB)","BODHADI BUJRUG (BHBK)","BHADRAK (BHC)","BADLI (BHD)","BHURKUNDA (BHKD)","BHILWARA (BHL)","BARAHAT (BHLE)","BHALKI (BHLK)","BHULANPUR (BHLP)","BHANDARIDAH (BHME)","BOLPUR S NIKTN (BHP)","VIDISHA (BHS)","BHATTU (BHT)","BHATIYA (BHTA)","BHANWAR TONK (BHTK)","BHITONI (BHTN)","BHATPAR RANI (BHTR)","BHUJ (BHUJ)","BARHARWA JN (BHW)","BIHARA (BHZ)","BHILAI (BIA)","BICHIA (BIC)","BIDADI (BID)","BIDAR (BIDR)","BELGAHNA (BIG)","BAIRAGARH (BIH)","BIJOOR (BIJR)","BHIRA KHERI (BIK)","BILDI (BILD)","BILIMORA JN (BIM)","BINA JN (BINA)","BORDI (BIO)","BHIWANDI ROAD (BIRD)","BHIND (BIX)","BARDOLI (BIY)","BAHJOI (BJ)","BAREJADI (BJD)","BHOJUDIH JN (BJE)","BIJNI (BJF)","BARA JAMDA (BJMD)","BIJAINAGAR (BJNR)","BIJNOR (BJO)","BIJAPUR (BJP)","BARRAJPUR (BJR)","BIJURI (BJRI)","BARAUNI JN (BJU)","BAJUD (BJUD)","BAJVA (BJW)","BANKA GHAT (BKG)","BANKHEDI (BKH)","BANDIKUI JN (BKI)","BARKUR (BKJ)","BONA KALU (BKL)","BIKANER JN (BKN)","BHAKTI NAGAR (BKNG)","BINDKI ROAD (BKO)","BAKHTIYARPUR JN (BKP)","BHALUKA ROAD F (BKRD)","BOKARO THERMAL (BKRO)","BOKARO STL CITY (BKSC)","BIKRAM SHILA (BKSL)","VALSAD (BL)","BARLAI (BLAX)","BHILAD (BLD)","BELDA (BLDA)","BHILDI (BLDI)","BILHAR GHAT (BLG)","BALANGIR (BLGR)","BALURGHAT (BLGT)","BELAKOBA (BLK)","BALAMU JN (BLM)","BHALUMASKA (BLMK)","BHALUKMARA (BLMR)","BOLINNA DOABA (BLND)","BADULIPAR (BLPR)","BILPUR (BLPU)","BILASPUR ROAD (BLQR)","BALASORE (BLS)","BALOTRA JN (BLT)","BELTHARA ROAD (BLTR)","BILHAUR (BLU)","BALAWALI (BLW)","BUDHLADA (BLZ)","BAMRA (BMB)","BISSAMCUTTACK (BMCK)","BHIMADOLU (BMD)","BARMER (BME)","BASMAT (BMF)","BETAMCHERLA (BMH)","BAMNIA (BMI)","BAPUDM MOTIHARI (BMKI)","BAMLA (BMLL)","BOLARUM (BMO)","BIKRAMPUR (BMR)","BEGAMPET (BMT)","BAMHRAULI (BMU)","BIBINAGAR (BN)","BANGALORE CANT (BNC)","BANGALORE EAST (BNCE)","BANDA JN (BNDA)","BONDAMUNDA (BNDM)","BUNIADPUR (BNDP)","BOHANI (BNE)","BONGAIGAON (BNGN)","BUDNI (BNI)","BANSTHALI NIWAI (BNLW)","BARNALA (BNN)","BHANAPUR (BNP)","BHAGWANPUR (BNR)","BANBASA (BNSA)","BHARTHANA (BNT)","BANTAWALA (BNTL)","BANDAKPUR (BNU)","BINNAGURI (BNV)","BHANVAD (BNVD)","BHIWANI (BNW)","BHIWANI CITY (BNWC)","BIDHAN NAGAR (BNXR)","BADSHAHNAGAR (BNZ)","BANGROD (BOD)","BARSOI JN (BOE)","BAROG (BOF)","BHAIRONGARH (BOG)","BHOJO (BOJ)","BHOKAR (BOKR)","BOINDA (BONA)","BOISAR (BOR)","BAGHDOGRA (BORA)","BHADOHI (BOY)","BARRACKPORE (BP)","BELAMPALLI (BPA)","BADARPUR JN (BPB)","BERHAMPORE CRT (BPC)","BANAPURA (BPF)","BELPAHAR (BPH)","BHILAI PWR HS (BPHB)","BHUGAON (BPK)","BHOPAL JN (BPL)","BARIPADA (BPO)","BAPATLA (BPP)","BALHARSHAH (BPQ)","BHOJIPURA JN (BPR)","BARPETA ROAD (BPRD)","BALPUR HALT (BPRH)","BANKURA (BQA)","BOMMIDI (BQI)","BIGHAPUR (BQP)","BHILAINAGAR (BQR)","BARANG (BRAG)","VADODARA JN (BRC)","BHANDARA ROAD (BRD)","BHARWARI (BRE)","BARGARH (BRG)","BARGARH ROAD (BRGA)","BARAIGRAM JN (BRGM)","BHERAGHAT (BRGT)","BARGAWAN (BRGW)","BAIKUNTHPUR RD (BRH)","BRAJRAJNAGAR (BRJN)","BAHRAICH (BRK)","BARKA KANA (BRKA)","BERMO (BRMO)","BARPALI (BRPL)","BIRAPATTI (BRPT)","BARAKAR (BRR)","BIYAVRA RAJGARH (BRRG)","BIRSINGHPUR (BRS)","BHAIROGANJ (BRU)","BARUD (BRUD)","BORVIHIR (BRVR)","BARWADIH JN (BRWD)","BAREILLY (BRY)","BARHIYA (BRYA)","BARETA (BRZ)","VARANASI JN (BSB)","BULANDSHAHR (BSC)","BHUSANDPUR (BSDP)","BADSHAHPUR (BSE)","BASUGAON (BSGN)","BASUKINATH (BSKH)","BHUSAVAL JN (BSL)","BILASPUR JN (BSP)","BASSI PATHANAM (BSPN)","BISHRAMPUR (BSPR)","BANSPANI (BSPX)","BANSIPUR (BSQP)","VASAI ROAD (BSR)","BAGEVADI RD (BSRX)","BASTI (BST)","BASANTAPUR (BSTP)","BASAR (BSX)","BARKISALALYA (BSYA)","BHARWA SUMERPUR (BSZ)","BIHTA (BTA)","BUTI BORI (BTBR)","BALAGHAT JN (BTC)","BOTAD JN (BTD)","BHARATPUR JN (BTE)","BASHARATGANJ (BTG)","BETTIAH (BTH)","BHATINDA JN (BTI)","BISHNATHGANJ (BTJ)","BHATKAL (BTJL)","BANKATA (BTK)","BHARAT KUP (BTKP)","BABATPUR (BTP)","BETNOTI (BTQ)","BANTHRA (BTRA)","BASTA (BTS)","BHATNI JN (BTT)","BITRAGUNTA (BTTR)","BARAUT (BTU)","BAITARANI ROAD (BTV)","BARSI TOWN (BTW)","BELA TAL (BTX)","BETHUADAHARI (BTY)","BASWA (BU)","BARADWAR (BUA)","BUNDI (BUDI)","BADMAL (BUDM)","BAGAHA (BUG)","BURHAR (BUH)","BALLIA (BUI)","BARIARPUR (BUP)","BABUPETH (BUPH)","BARGI (BUQ)","BURNPUR (BURN)","BAYTU (BUT)","BURHWAL (BUW)","BHANDAK (BUX)","BABHNAN (BV)","BHAVNAGAR TRMUS (BVC)","BALLABGARH (BVH)","BORIVALI (BVI)","BIKKAVOLU (BVL)","BISWAN (BVN)","BHAVANI NAGAR (BVNR)","BHAVANAGAR PARA (BVP)","BHILAVDI (BVQ)","BHIMAVARAM JN (BVRM)","BHIMAVARAM TOWN (BVRT)","BHADAURA (BWH)","BILWAI (BWI)","BHAWANIPATNA (BWIP)","BAWAL (BWL)","BHAWANI MANDI (BWM)","BARDDHAMAN JN (BWN)","BARWA SAGAR (BWR)","BIJWASAN (BWSN)","BANGARAPET (BWT)","BALOD (BXA)","BOKAJAN (BXJ)","BANDARKHAL (BXK)","BELRAYAN (BXM)","BAYANA JN (BXN)","BARPATHAR (BXP)","BUXAR (BXR)","BORDHAL (BXY)","BYADGI (BYD)","BELHA (BYL)","BANAHI (BYN)","MOOKAMBIKA ROAD (BYNR)","BHATAPARA (BYT)","VIJAYAWADA JN (BZA)","BILGA (BZG)","BAZARSAU (BZLE)","BHIMSEN (BZM)","BAGNAN (BZN)","BARSOLA (BZO)","BISRA (BZR)","BETUL (BZU)","BASAI (BZY)","CHAKIA (CAA)","CHHANERA (CAER)","CHANDA FORT (CAF)","CHHABRA GUGOR (CAG)","CHANPATIA (CAI)","KANNUR (CAN)","CHATRAPUR (CAP)","KANYAKUMARI (CAPE)","CHUNAR (CAR)","COIMBATORE JN (CBE)","COIMBATORE NRTH (CBF)","CHACHAURA BNGJ (CBK)","CUMBUM (CBM)","CHIT BARAGAON (CBN)","CHAIBASA (CBSA)","CHURAIBARI (CBZ)","CHAURI CHAURA (CC)","CHINCHVAD (CCH)","KAKINADA TOWN (CCT)","CHANDRAPUR (CD)","CHANDIGARH (CDG)","CHANDRAKONA RD (CDGR)","CHIDAMBARAM (CDM)","CHANDAULI MJHWR (CDMR)","CHHARODI (CE)","CHENGALPATTU (CGL)","CHIRGAON (CGN)","CHANDAN NAGAR (CGR)","CHANGANASERI (CGY)","CHANDAUSI JN (CH)","CHAWAPALL (CHA)","CHABUA (CHB)","CHANDIA ROAD (CHD)","SRIKAKULAM ROAD (CHE)","CHAUKHANDI (CHH)","CHIPLUN (CHI)","CHATA (CHJ)","CHAKKI BANK (CHKB)","CHOLA (CHL)","CHAUK (CHOK)","CHHAPI (CHP)","CHILKAHAR (CHR)","CHINNA SALEM (CHSM)","CHARVATTUR (CHV)","CHARLAPALLI (CHZ)","CHHAPRA KACHERI (CI)","CHILBILA JN (CIL)","KANCHIPURAM (CJ)","CHINNA GANJAM (CJM)","CHHATNA (CJN)","CHAUTH KA BRWRA (CKB)","CHARKHI DADRI (CKD)","CHAKDAYALA (CKDL)","CHIKHLI (CKHS)","CHALAKUDI (CKI)","CHAKARPUR (CKK)","CHIKNI ROAD (CKNI)","CHAKRADHARPUR (CKP)","CHIKODI ROAD (CKR)","CHITRAKOT (CKTD)","CHAKULIA (CKU)","CHILIKIDARA (CLDR)","CHANDLODIYA (CLDY)","CHHULHA (CLF)","KAHALGAON (CLG)","COLONELGANJ (CLJ)","CHILKA (CLKA)","CASTLE ROCK (CLR)","KOZHIKODE (CLT)","CHILAKALAPUDI (CLU)","CHIRALA (CLX)","CINNAMARA (CMA)","CHAU MAHLA (CMU)","CHIMA PAHAD (CMW)","CHANDERIYA (CNA)","KANPUR CENTRAL (CNB)","CHINCHLI (CNC)","CHANDUR (CND)","CHANDUR BAZAR (CNDB)","CHANDI MANDIR (CNDM)","CHANDRANATHPUR (CNE)","CHENGANNUR (CNGR)","CHANDIL JN (CNI)","CHANDOK (CNK)","CANCONA (CNO)","CHAINPUR (CNPR)","CHUCHURA (CNS)","KAKINADA PORT (COA)","CHEOKI (COI)","CHITTAURGARH (COR)","KANPUR ANWRGANJ (CPA)","CHHIPADOHAR (CPDR)","CHAMPA (CPH)","KAPTANGANJ JN (CPJ)","CHAPARMUKH JN (CPK)","CHAMPANER RD JN (CPN)","CHIPURUPALLE (CPP)","CHHAPRA (CPR)","CHAND SIAU (CPS)","CHANNAPATNA (CPT)","CHOPAN (CPU)","CHERUKARA (CQA)","CHITTARANJAN (CRJ)","CARMELARAM (CRLM)","CHAREGAON (CRN)","CHAUTARA (CROA)","CHANDRAPURA (CRP)","KARAGOLA ROAD (CRR)","CHIRAYINKIL (CRY)","CHAUSA (CSA)","SHIVAJI BRIDGE (CSB)","CHALISGAON JN (CSN)","MUMBAI CST (CSTM)","CHITTAPUR (CT)","CUTTACK (CTC)","CHOTI KHATU (CTKT)","CHETTINAD (CTND)","CHITTOOR (CTO)","CHATRA (CTR)","CHITYALA (CTYL)","CHURK (CUK)","CUDDALORE PORT (CUPJ)","CHURU (CUR)","CHAURA (CUX)","KOVILPATTI (CVP)","CHORVAD ROAD (CVR)","CHAINWA (CW)","CHHINDWARA JN (CWA)","DATIA (DAA)","DHARMABAD (DAB)","DHABAN (DABN)","DAKHINESWAR (DAKE)","DALIGANJ (DAL)","DARA (DARA)","DHASA JN (DAS)","DHANUVACHAPURAM (DAVM)","DABRA (DBA)","DHUBRI (DBB)","DEOBAND (DBD)","DEVBALODA CHRDA (DBEC)","DARBHANGA JN (DBG)","DABHAURA (DBR)","DIBRUGARH (DBRG)","DIBRUGARH TOWN (DBRT)","DODBALLAPUR (DBU)","DIGBOI (DBY)","DAMCHARA (DCA)","DAUND JN (DD)","DURAUNDHA JN (DDA)","DUNDI (DDCE)","DONDAICHA (DDE)","DHANDARI KALAN (DDL)","DEHRADUN (DDN)","DAUDPUR (DDP)","DADAR (DDR)","DEBAGRAM (DEB)","DELHI CANTT (DEC)","DELHI S ROHILLA (DEE)","DELANG (DEG)","DEHU ROAD (DEHR)","DIYODAR (DEOR)","DEORIA SADAR (DEOS)","DADRI (DER)","DESARI (DES)","DINDIGUL JN (DG)","DIGHWARA (DGA)","DONGARGARH (DGG)","DIGHA FLAG STN (DGHA)","DEOGHAR (DGHR)","DUNGRI (DGI)","DHULIAN GANGA (DGLE)","DURGAUTI (DGO)","DURGAPUR (DGR)","DIGARU (DGU)","DHEENA (DHA)","DHACA CANTT (DHCA)","DAHOD (DHD)","DHRANGDHRA (DHG)","DHULE (DHI)","DHANBAD JN (DHN)","DHONE (DHNE)","DHAULPUR (DHO)","DAPPAR (DHPR)","DHIRERA (DHRR)","DHAMARA GHAT (DHT)","DHARIWAL (DHW)","DIDWANA (DIA)","DUGGIRALA (DIG)","DILAWARNAGAR (DIL)","DIVINE NAGAR (DINR)","DISA (DISA)","DARJEELING (DJ)","DAOTUHAJA (DJA)","DULIAJAN (DJG)","TO DARJEELING (DJRZ)","DONAKONDA (DKD)","DIHAKHO (DKE)","DORNAKAL JN (DKJ)","DAKANIYA TALAV (DKNT)","DEVAKOTTAI ROAD (DKO)","DHULKOT (DKT)","DELHI KISHANGNJ (DKZ)","DALADI (DL)","DAULATABAD (DLB)","DALAUDA (DLD)","DHALGAON (DLGN)","DELHI (DLI)","DHOLA JN (DLJ)","DALKOLHA (DLK)","DILDARNAGAR JN (DLN)","DALGAON (DLO)","DAULATPUR HAT (DLPH)","DALELNAGAR (DLQ)","DULLAHAPUR (DLR)","DUMRI BIHAR (DMBR)","DHEMAJI (DMC)","DOMINGARH (DMG)","DHAMALGAON (DMGN)","DHARMAVARAM JN (DMM)","DHAMANGAON (DMN)","DAMANJODI (DMNJ)","DAMOH (DMO)","DHARMPUR HMCHL (DMP)","DHARMANAGAR (DMR)","DUMURIPUT (DMRT)","DUMRI HALT (DMRX)","DIMAPUR (DMV)","DALMAU JN (DMW)","DEGANA JN (DNA)","DANDUPUR (DND)","DANEA (DNEA)","DHANAKYA (DNK)","DHENKANAL (DNKL)","DHANMANDAL (DNM)","DINA NAGAR (DNN)","DANAPUR (DNR)","DHANAURI (DNRE)","DUNGARPUR (DNRP)","DANTAN (DNT)","DANIYAWAN BZR H (DNWH)","DAUSA (DO)","DORAHA (DOA)","DHODHAR (DOD)","DEORI (DOE)","DHOLI (DOL)","DEHRI ON SONE (DOS)","DEOTALA (DOTL)","DURGAPURA (DPA)","DHARMAPURI (DPJ)","DANAULI PHLWRIA (DPL)","DHAMPUR (DPR)","DANGOAPOSI (DPS)","DIPHU (DPU)","DEPUR PH (DPUR)","DHUPGURI (DQG)","DHANERA (DQN)","DADAR (DR)","DAHANU ROAD (DRD)","DHARHARA (DRH)","DEROL (DRL)","DAURALA (DRLA)","DASHARATHPUR (DRTP)","KADUR (DRU)","DALLI RAJHARA (DRZ)","DELHI SHAHDARA (DSA)","DELHI SAFDARJNG (DSJ)","DESHNOK (DSO)","DALSINGH SARAI (DSS)","DITOKCHERRA (DTC)","DALTONGANJ (DTO)","DHAURA (DUA)","DABTARA (DUB)","DUBAHA (DUBH)","DUDHANI (DUD)","DHURI JN (DUI)","DUBRAJPUR (DUJ)","DUMKA (DUMK)","DUMRAON (DURE)","DURG (DURG)","DUSI (DUSI)","DUVVADA (DVD)","DAVANGERE (DVG)","DEVLALI (DVL)","DWARKA (DWK)","DHAUNI (DWLE)","DOIWALA (DWO)","DWARAPUDI (DWP)","DHARWAR (DWR)","DEWAS (DWX)","DHARANGAON (DXG)","DUDDHINAGAR (DXN)","DARYABAD (DYD)","DASUYA (DZA)","ERODE JN (ED)","ELURU (EE)","EKCHARI (EKC)","EKLAKHI (EKI)","EKAMBARAKUPPAM (EKM)","EKMA (EKMA)","EKANGARSARAI (EKR)","ELIMALA (ELM)","ERANIEL (ERL)","ERNAKULAM TOWN (ERN)","ERNAKULAM JN (ERS)","ITARSI JN (ET)","ETTUMANUR (ETM)","ETTAPUR ROAD (ETP)","ETAWAH (ETW)","FALNA (FA)","FATEHNAGAR (FAN)","FARRUKHABAD (FBD)","FORBESGANJ (FBG)","FAIZABAD JN (FD)","FARIDABAD (FDB)","FARIDKOT (FDK)","FARIDABAD NW TN (FDN)","FATEHGARH (FGR)","FATEHGARH SAHIB (FGSB)","FARAH TOWN (FHT)","FEROK (FK)","FURKATING JN (FKG)","FAKIRAGRAM JN (FKM)","PHULERA JN (FL)","FALAKATA (FLK)","KCG FALAKNUMA (FM)","FATEH SINGHPURA (FSP)","FURSATGANJ (FTG)","FATEHPUR (FTP)","FATEHPUR SIKRI (FTS)","FATWA (FUT)","FAIZULLAPUR (FYZ)","FIROZABAD (FZD)","FIROZPUR CANT (FZR)","GONDIA JN (G)","GEVRA ROAD (GAD)","GOALDIH (GADH)","GANDHINAGAR JPR (GADJ)","GALGALIA (GAGA)","GANESHGANJ (GAJ)","GANJAM (GAM)","GANGAGANJ (GANG)","GHANAULI (GANL)","GURPA (GAP)","GADARWARA (GAR)","GAYA JN (GAYA)","GAURI BAZAR (GB)","GARHBETA (GBA)","GAURIBIDANUR (GBD)","GULABPURA (GBP)","GOVINDPUR ROAD (GBX)","GACHHIPURA (GCH)","GHAZIPUR CITY (GCT)","GONDA JN (GD)","GODHRA JN (GDA)","GIDDARBAHA (GDB)","GADAG JN (GDG)","GONDAL (GDL)","GUDUR JN (GDR)","GUDIVADA JN (GDV)","GHOKSADANGA (GDX)","GHORADONGRI (GDYA)","GUNDARDEHI (GDZ)","GULEDAGUDDA RD (GED)","GHOGA (GGA)","GANGAPUR CITY (GGC)","GOSHAINGANJ (GGJ)","GURGAON (GGN)","GANGRAR (GGR)","GHUGHULI (GH)","GARWA ROAD (GHD)","GHAGWAL (GHGL)","GARHI HARSARU (GHH)","GURSAHAIGANJ (GHJ)","GARHWA (GHQ)","GIDHAUR (GHR)","GHUM (GHUM)","GUWAHATI (GHY)","GIDDALUR (GID)","GANDHIDHAM BG (GIMB)","GUJHANDI (GJD)","GOLDINGANJ (GJH)","GAJRAULA JN (GJL)","GANGSAR JAITU (GJUT)","GOLA GOKARANATH (GK)","GORAKHPUR CANT (GKC)","GUSKARA (GKH)","GOLAKGANJ JN (GKJ)","GOKAK ROAD (GKK)","GORAKHPUR JN (GKP)","GARLA (GLA)","GULABHGANJ (GLG)","GOLAGHAT (GLGT)","GULAOTHI (GLH)","GOLLAPROLU (GLP)","GOALPARA TOWN (GLPT)","GUMANI (GMAN)","GURAMKHEDI (GMD)","GIRIMAIDAN (GMDN)","GAMHARIA (GMH)","GUMIA (GMIA)","NSC BOSE J GOMO (GMO)","GAHMAR (GMR)","GARHMUKTESAR (GMS)","GONEANA (GNA)","GANDHINAGAR CAP (GNC)","GAURIGANJ (GNG)","GANGADHARPUR (GNGD)","GANGAKHER (GNH)","GHANPUR (GNP)","GHONSOR (GNS)","GUNTUR JN (GNT)","GANAUR (GNU)","GONDWANAVISAPUR (GNVR)","GANGIWARA (GNW)","GOHAD ROAD (GOA)","PONMLAI GLD RCK (GOC)","GOSSAIGAON HAT (GOGH)","GAROT (GOH)","GOKARNA ROAD (GOK)","GOILKERA (GOL)","GOGAMUKH (GOM)","GOP JAM (GOP)","GOTAN (GOTN)","GOVINDPURI (GOY)","RAJ GANGPUR (GP)","GHATPRABHA (GPB)","GUMMIDIPUNDI (GPD)","GARPOS (GPH)","GHORPURI (GPR)","GOHPUR (GPZ)","GURLA (GQL)","GULBARGA (GR)","GHARAUNDA (GRA)","G.RAMACHANDRAPU (GRCP)","GIRIDIH (GRD)","GORAUL (GRL)","GANGARAMPUR (GRMP)","GARHI MANIKPUR (GRMR)","GURRA (GRO)","GURARU (GRRU)","GAURA (GRX)","GORAYA (GRY)","GURDASPUR (GSP)","GOSALPUR (GSPR)","GETOR JAGATPURA (GTJT)","GHUTKU (GTK)","GUNTAKAL JN (GTL)","GHATAMPUR (GTM)","GOMATI NAGAR (GTNR)","GHATSILA (GTS)","GAUTAMSTHAN (GTST)","GOMTA (GTT)","GALUDIH (GUD)","GARH JAIPUR (GUG)","GULDHAR (GUH)","GUNA (GUNA)","GANAGAPUR ROAD (GUR)","GURUVAYUR (GUV)","GHOLVAD (GVD)","GOVINDGARH (GVG)","GARIVIDI (GVI)","GUDLAVALLERU (GVL)","GODAVARI (GVN)","GANJ DUNDWARA (GWA)","GADWAL (GWD)","GWALIOR (GWL)","GAUSHALA (GWS)","GOWDAVALLI (GWV)","GOOTY (GY)","GUDIYATTAM (GYM)","GYANPUR ROAD (GYN)","GHAZIABAD (GZB)","GULZARBAGH (GZH)","N GHAZIABAD (GZN)","GAZOLE (GZO)","HARIPPAD (HAD)","HINDAUN CITY (HAN)","HAPA (HAPA)","HAMIRPUR ROAD (HAR)","HASSAN (HAS)","HOSHANGABAD (HBD)","HOWBADH JABLPUR (HBG)","HABIBGANJ (HBJ)","HARICHANDANPUR (HCNR)","HARCHANDPUR (HCP)","HARISCHANDRPUR (HCR)","HARDA (HD)","HIRNODA (HDA)","HALDIBARI (HDB)","HARDAS BIGHA (HDE)","HANDIA KHAS (HDK)","HODAL (HDL)","HAIDARNAGAR (HDN)","HALDWANI (HDW)","HIMAYATNAGAR (HEM)","HAFLONG HILL (HFG)","HOTGI (HG)","HAIDERGARH (HGH)","HARANGUL (HGL)","HINGANGHAT (HGT)","HIJILLI (HIJ)","HILSA (HIL)","HALDIPADA (HIP)","HARINAGAR (HIR)","HOJAI (HJI)","HARANGAJAO (HJO)","HAJIPUR JN (HJP)","HIRAKUD (HKG)","HOLE ALUR (HLAR)","HALDI ROAD (HLDD)","HALDAUR (HLDR)","HOLE NARSIPUR (HLN)","HILARA (HLX)","HALDIA (HLZ)","HAMIRGARH (HMG)","HANUMANGARH JN (HMH)","HELEM (HML)","HIMMATNAGAR (HMT)","HARMUTI (HMY)","HATHBANDH (HN)","HONNAVAR (HNA)","HINGOLI DECCAN (HNL)","HANSI (HNS)","HAMITONGANJ (HOJ)","HARIPUR (HP)","HATPURAINI (HPLE)","HASANPUR ROAD (HPO)","HARPALPUR (HPP)","HOSPET JN (HPT)","HAPUR (HPU)","HARRI (HRB)","HIRDAGARH (HRG)","HARDOI (HRI)","HIRA NAGAR (HRNR)","HARPALGANJ (HRPG)","HARIHAR (HRR)","HATHRAS JN (HRS)","HARNAUT (HRT)","HARRAWALA (HRW)","HASIMARA (HSA)","HARSAULI (HSI)","HARISHANKER RD (HSK)","HASANPARTHI RD (HSP)","HISAR (HSR)","HOSUR (HSRA)","HOSHIARPUR (HSX)","HATHRAS CITY (HTC)","HATIA (HTE)","HATKANAGALE (HTK)","HATIKHALI (HTL)","HATHIDAH JN (HTZ)","HINDUPUR (HUP)","HALVAD (HVD)","HAVERI (HVR)","HARIDWAR JN (HW)","HOWRAH JN (HWH)","CUDDAPAH (HX)","HYDERABAD DECAN (HYB)","HAIAGHAT (HYT)","HAZARIBAGH RD (HZD)","HAFIZPUR (HZR)","INDARA JN (IAA)","ICHAULI (ICL)","INDARGARH (IDG)","IDGAH AGRA JN (IDH)","INDI ROAD (IDR)","IGATPURI (IGP)","IRUGUR (IGU)","IRINJALAKUDA (IJK)","IKKAR (IKK)","IKLEHRA (IKR)","INDORE JN BG (INDB)","IDAPLLI (IPL)","ICHCHPURAM (IPM)","ISLAMPUR (IPR)","ISARDA (ISA)","ISMAILA HARYANA (ISM)","ITOLA (ITA)","ITWARI (ITR)","IZZATNAGAR (IZN)","JALNA (J)","JHALIDA (JAA)","JAIS (JAIS)","JHAJHA (JAJ)","JAWALI (JAL)","JAMNAGAR (JAM)","JAMA (JAMA)","JARANGDIH (JAN)","JAORA (JAO)","JAMMU TAWI (JAT)","JOGBANI (JBN)","JABALPUR (JBP)","JADCHERLA (JCL)","JAGDALPUR (JDB)","JALESWAR (JER)","JEUR (JEUR)","JAGADISHPUR (JGD)","JAGESHARGANJ (JGJ)","JHARGRAM (JGM)","JAGRAON (JGN)","JOGENDRANAGAR (JGNR)","JASWANTNAGAR (JGR)","JEHANABAD (JHD)","JAKHAL JN (JHL)","JAKHIM (JHN)","JHANSI JN (JHS)","JHALAWAR ROAD (JHW)","JAGI ROAD (JID)","JIND JN (JIND)","JIAGANJ (JJG)","JHINJHAK (JJK)","JAJPUR K ROAD (JJKR)","JEJURI (JJR)","JAKHVADA (JKA)","JAKHALABANDHA (JKB)","JUKEHI (JKE)","JAKHANIAN (JKN)","JAKHAPURA (JKPR)","JALGAON JN (JL)","JARWAL ROAD (JLD)","JALALGANJ (JLL)","JAKHALAUN (JLN)","JETALSAR JN (JLR)","JALESAR ROAD (JLS)","JHALWARA (JLW)","JALAMB JN (JM)","JAMDHA (JMD)","JAMUNAMUKH (JMK)","JAMIKUNTA (JMKT)","JAMALPUR JN (JMP)","JAMTARA (JMT)","JAMUI (JMU)","JAMBARA (JMV)","JULANA (JNA)","JUNAGADH JN (JND)","JANGHAI JN (JNH)","JANDIALA (JNL)","JUNNOR DEO (JNO)","JANAKPUR ROAD (JNR)","JAUNPUR JN (JNU)","JANWAL (JOA)","ASALPUR JOBNER (JOB)","JOYCHANDI PAHAR (JOC)","JOGAL (JOL)","JAUNPUR CITY (JOP)","JORAI (JOQ)","JALOR (JOR)","JAIPUR (JP)","JALALPUR DHAI (JPD)","JALPAIGURI ROAD (JPE)","JALPAIGURI (JPG)","JHANTIPAHARI (JPH)","JAPLA (JPL)","JOGIGHOPA (JPZ)","JARAIKELA (JRA)","JALANDHAR CANT (JRC)","JUGPURA (JRG)","JERUWA KHERA (JRK)","JANGIPUR ROAD (JRLE)","JAROLI (JRLI)","JAIRAMNAGAR (JRMG)","JIRANIA (JRNA)","JUGAUR (JRR)","CHIKJAJUR JN (JRU)","JHARSUGUDA JN (JSG)","JAISALMER (JSM)","JASIDIH JN (JSME)","JAYASINGPUR (JSP)","JASRA (JSR)","JARANDESHWAR (JSV)","JAGATBELA (JTB)","JATINGA (JTG)","JAITHARI (JTI)","JOLARPETTAI (JTJ)","JUTOGH (JTO)","JORHAT TOWN (JTTN)","JAITWAR (JTW)","JODHPUR JN (JU)","JALANDHAR CITY (JUC)","JAGADHRI (JUD)","JAGADHRI WSHOP (JUDW)","JUJUMURA (JUJA)","JORAWARNAGAR JN (JVN)","JAWAI BANDH (JWB)","JAWAD ROAD (JWO)","JWALAPUR (JWP)","JAYNAGAR (JYG)","JAI SAMAND ROAD (JYM)","JEYPORE (JYP)","KHANDALA (KAD)","KALIYANGANJ (KAJ)","KARANJGAON (KAJG)","KALLAL (KAL)","KAMAKHYAGURI (KAMG)","KHANA JN (KAN)","KANOH (KANO)","KALIANPUR (KAP)","KALUPARA GHAT (KAPG)","KARNA (KAR)","KIRATPUR SAHIB (KART)","KANAS ROAD (KASR)","KHATAULI (KAT)","KANTHI P H (KATI)","KATOL (KATL)","KARWAR (KAWR)","KAYAR (KAYR)","KANTABANJI (KBJ)","KOPPAL (KBL)","KOTABOMMALI (KBM)","KARBIGWAN (KBN)","KABAKAPUTTUR (KBPR)","KANJARI BORIYAV (KBRV)","KHOIRABARI (KBY)","KUCHMAN (KCA)","KRISHNA CANAL (KCC)","KURICHEDU (KCD)","KACHEGUDA (KCG)","KALLKIRI (KCI)","KASIMPUR (KCJ)","KACHHIA BRIDGE (KCO)","KRISHNA CH PURA (KCV)","KOCHUVELI (KCVL)","KEDGAON (KDG)","KARCHHA (KDHA)","KENDUJHARGARH (KDJR)","KESAMUDRAM (KDM)","KODIYAR MANDIR (KDMR)","KADAYNALLUR (KDNL)","KONDAPURAM (KDP)","KUMEDPUR (KDPR)","KADAMBUR (KDU)","KANDAGHAT (KDZ)","KATRA (KEA)","KARENGI (KEG)","KAPSETI (KEH)","KASHI (KEI)","KATHLEEGHAT (KEJ)","KARKHELI (KEK)","KEM (KEM)","KOIRIPUR (KEPR)","KIRIHRAPUR (KER)","KOPARIA (KFA)","KHAGA (KGA)","KARGI ROAD (KGB)","KHAGARIA JN (KGG)","KENGERI (KGI)","KUPGAL (KGL)","KHAGRAGHAT ROAD (KGLE)","KATHGODAM (KGM)","KURSEONG (KGN)","KHARAGPUR JN (KGP)","KASARAGOD (KGQ)","KHONGSARA (KGS)","KANGINHAL (KGX)","KAHILIYA (KH)","KHANNA BANJARI (KHBJ)","KHODIYAR (KHD)","KHED (KHED)","KUSMHI (KHM)","KHATIMA (KHMA)","KUNDA HARNAMGNJ (KHNM)","KUMBHRAJ (KHRJ)","KHARAK (KHRK)","KHARSIA (KHS)","SRI KALAHASTI (KHT)","KHATU (KHTU)","KHURHAND (KHU)","KONDAPALLI (KI)","KARAIKAL (KIK)","KIM (KIM)","KAPASAN (KIN)","KHALILPUR (KIP)","KATIHAR JN (KIR)","KAPILAS ROAD (KIS)","KHALLIKOT (KIT)","KIUL JN (KIUL)","KAJGAON (KJ)","KARAJGI (KJG)","KAJRA (KJH)","KHAJAULI (KJI)","KRISHNARAJAPURM (KJM)","KANNAUJ (KJN)","KARJAT (KJT)","KHURJA CITY (KJY)","KHADKI (KK)","KANKI (KKA)","KANKAHA (KKAH)","KARAK BEL (KKB)","KURUKSHETRA JN (KKDE)","KARAIKKUDI JN (KKDI)","KAKIRIGUMMA (KKGM)","KAKARGHATTI (KKHT)","KARKELI (KKI)","KAKORI (KKJ)","KAIKOLUR (KKLR)","KAMALAPURAM (KKM)","KHIRKIYA (KKN)","KOT KAPURA (KKP)","KALLAKKUDI PLGH (KKPM)","KOLLIKHUTAHA (KKTA)","KANAKPURA (KKU)","KANKAVALI (KKW)","KHERLI (KL)","KULPAHAR (KLAR)","KIRAOLI (KLB)","KHALILABAD (KLD)","KALUNGA (KLG)","KAMALGANJ (KLJ)","KALKA (KLK)","KALOL (KLL)","KALANAUR KALAN (KLNK)","KOTALPUKUR (KLP)","KAILASAPURAM (KLPM)","KHALARI (KLRE)","KOLARAS (KLRS)","KULITALAI (KLT)","KALMITAR (KLTR)","KALLURU (KLU)","KHAMBHALIYA (KMBL)","KAMAREDDI (KMC)","KODUMUDI (KMD)","KARIMUDDIN PUR (KMDR)","KAIMGANJ (KMJ)","KAMTAUL (KML)","KUMARDUBI (KMME)","KUCHAMAN CITY (KMNC)","KAMALNAGAR (KMNR)","KUMBLA (KMQ)","KARAMNASA (KMS)","KHAMMAM (KMT)","KUMARHATTI (KMTI)","KUMBAKONAM (KMU)","KATNI MURWARA (KMZ)","KADALUNDI (KN)","KANDRA (KND)","KISHANGANJ (KNE)","KRISHNGR CTY JN (KNJ)","KALANWALI (KNL)","KANALAS JN (KNLS)","KHANNA (KNN)","KHANAPUR (KNP)","KENDRAPARA ROAD (KNPR)","KENDPOSI (KNPS)","KANTH (KNT)","KINWAT (KNVT)","KHANDWA (KNW)","KOSGI (KO)","KOLKATA (KOAA)","KHODRI (KOI)","KOKRAJHAR (KOJ)","KOLNUR (KOLR)","KUDALNAGAR (KON)","KHUSROPUR (KOO)","C SHAHUMHARAJ T (KOP)","KOTA JN (KOTA)","KODURU (KOU)","KIRLOSKARVADI (KOV)","KAMPTEE (KP)","KATPADI JN (KPD)","KOPARGAON (KPG)","KARPURIGRAM (KPGM)","KALPI (KPI)","KUPPAM (KPN)","KAPAN (KPNA)","KALAPIPAL (KPP)","KANNAPURAM (KPQ)","KALYANPUR ROAD (KPRD)","KOTAPAR ROAD (KPRR)","KESHORAI PATAN (KPTN)","KASHIPUR (KPV)","KARUNAGAPALLI (KPY)","KALACHAND (KQI)","KOTIKULAM (KQK)","KODAIKANAL ROAD (KQN)","KODERMA (KQR)","KURGUNTA (KQT)","KAMARKUNDU (KQU)","KAREPALLI (KRA)","KHARIAR ROAD (KRAR)","KORBA (KRBA)","KHUDIRAM B PUSA (KRBP)","KARAD (KRD)","KARTARPUR (KRE)","KOREGAON (KRG)","KHAIRTHAL (KRH)","KORAI HALT (KRIH)","KHURJA JN (KRJ)","KURALI (KRLI)","KARAILA ROAD JN (KRLR)","KARMALI (KRMI)","KARIMNAGAR (KRMR)","KHORASON ROAD (KRND)","KRISHNARAJNAGAR (KRNR)","KURNOOL CITY (KRNT)","KORAPUT (KRPU)","KARUR (KRR)","KARISATH (KRS)","KHARSALIYA (KRSA)","KRISHNASHILLA (KRSL)","KADIRI (KRY)","KHETA SARAI (KS)","KOSAMBA JN (KSB)","KASHI CHAK (KSC)","KESHOD (KSD)","KHALISPUR (KSF)","KISHANGARH (KSG)","KALI SINDH (KSH)","KASGANJ (KSJ)","KRISHNA (KSN)","KESINGA (KSNG)","KISHANPUR (KSP)","KASARA (KSRA)","KOSI KALAN (KSV)","KOTSHILA (KSX)","KUMTA (KT)","KAITHALKUCHI (KTCH)","KATNI (KTE)","KEUTGUDA (KTGA)","KATRASGARH (KTH)","KOTHARI ROAD (KTHD)","KATHUA (KTHU)","KOTLI KALAN (KTKL)","KUTRALAM (KTM)","KOTMA (KTMA)","KUDRA (KTQ)","KATAREAH (KTRH)","KATHARA ROAD (KTRR)","KOTMI SONAN HLT (KTSH)","KUTTIPPURAM (KTU)","KOTTAVALASA (KTV)","KOTDWARA (KTW)","KATAKHAL JN (KTX)","KOTTAYAM (KTYM)","KULHARIA (KUA)","KUDACHI (KUD)","KUNDAPURA (KUDA)","KUDAL (KUDL)","KURSELA (KUE)","KAURHA (KUF)","KUMARGHAT (KUGT)","KHACHROD (KUH)","KARNAL (KUN)","KHURDPUR (KUPR)","KHURDA ROAD JN (KUR)","KHAJURAHO (KURJ)","KHUMTAI (KUTI)","KUHURI (KUU)","KHIRSADOH JN (KUX)","KUNEANGANJ (KVG)","KAVUTARAM (KVM)","KOVVUR (KVR)","KADAKAVUR (KVU)","KAVALI (KVZ)","KATWA (KWAE)","KHURIAL (KWE)","KAMPUR (KWM)","KARAUTA (KWO)","KHATIPURA (KWP)","KOELWAR (KWR)","KURDUVADI (KWV)","KAPURTHALA (KXH)","KARIMGANJ JN (KXJ)","KAMARBANDHA ALI (KXL)","KANSHBAHAL (KXN)","KARELI (KY)","KHURAI (KYE)","KAJRAT NAWADIH (KYF)","KAYANKULAM JN (KYJ)","KADIYAN (KYM)","KALYAN JN (KYN)","KOTTAPALLI (KYOP)","KAMAKHYA (KYQ)","KAILAHAT (KYT)","KHADA (KZA)","KURUMBUR (KZB)","KANHANGAD (KZE)","KAZIPET JN (KZJ)","KAZHAKUTTAM (KZK)","KULITTHURAI (KZT)","KULITTURAI WEST (KZTW)","KAYALPATTINAM (KZY)","LALITPUR (LAR)","LADNUN (LAU)","LABHA (LAV)","LAMBHUA (LBA)","LUCKNOW CITY (LC)","LONDA JN (LD)","LUDHIANA JN (LDH)","LEDO (LEDO)","LOWER HAFLONG (LFG)","LALGARH JN (LGH)","LALGOLA (LGL)","LALGOPALGANJ (LGO)","LANGTING (LGT)","LEHRA GAGA (LHA)","LAHLI (LHLL)","LOHARU (LHU)","LUCKNOW NE (LJN)","LANJIGARH ROAD (LJR)","LANKA (LKA)","LAKHERI (LKE)","LAXMIPUR ROAD (LKMR)","LAKHMINIA (LKN)","LUCKNOW NR (LKO)","LUCKEESARAI JN (LKR)","LUNKARANSAR (LKS)","LAL KUAN (LKU)","LELIGUMA (LLGM)","LALGUDI (LLI)","LALGANJ (LLJ)","LIMBDI (LM)","LUMDING JN (LMG)","LIMKHEDA (LMK)","LACHHMANPUR (LMN)","LAKSHMIBAI NGR (LMNR)","LILIYA MOTA (LMO)","LAKHIMPUR (LMP)","ALMATTI (LMT)","LOHIAN KHAS JN (LNK)","LONAVALA (LNL)","LONAND (LNN)","LUNI RICHHA (LNR)","LINGTI (LNT)","LINGAMPALLI (LPI)","LALPUR JAM (LPJ)","LAR ROAD (LRD)","LAKSAR JN (LRJ)","LASALGAON (LS)","LAHERIA SARAI (LSI)","LASUR (LSR)","LOISINGHA (LSX)","LAMTA (LTA)","LATHIDAD (LTD)","LATEHAR (LTHR)","LAKHTAR (LTR)","LATUR ROAD (LTRR)","LOKMANYATILAK T (LTT)","LUNI JN (LUNI)","LATUR (LUR)","LUSA (LUSA)","ALNAVAR JN (LWR)","LAKSWA (LXA)","MADHA (MA)","MANDI BAMORA (MABA)","MAHBUBABAD (MABD)","MADDUR (MAD)","MANGALAGIRI (MAG)","MANIKGARH (MAGH)","MAHE (MAHE)","MEHSI (MAI)","MANGALORE JN (MAJN)","MARARIKULAM (MAKM)","MALKHEDI (MAKR)","MALIYA MIYANA (MALB)","MANTHRALAYAM RD (MALM)","MANGAL MAHUDI (MAM)","MANINAGAR (MAN)","MAHANAGAR (MANG)","MONU (MANU)","MADGAON (MAO)","MORAPPUR (MAP)","MANGALORE CNTL (MAQ)","CHENNAI CENTRAL (MAS)","MAU JN (MAU)","MAUR (MAUR)","MARIAHU (MAY)","MORADABAD (MB)","MAHOBA (MBA)","MURSHIDABAD (MBB)","MUNABAO (MBF)","MAIBANG (MBG)","MADHUBANI (MBI)","MAMBALAM (MBM)","MARWAR BHINMAL (MBNL)","MAHBUBNAGAR (MBNR)","MADHOSINGH (MBS)","MANDI DABWALI (MBY)","MECHEDA (MCA)","MANCHIRYAL (MCI)","MUKUNDARAYAPURM (MCN)","MIRCHADHORI (MCQ)","MECHERI ROAD (MCRD)","MANCHESWAR (MCS)","MULACALACHERUVU (MCU)","MADAR (MD)","MANDI DIP (MDDP)","MAKHDUMPUR GAYA (MDE)","MUHAMMADGANJ (MDJ)","MANDAL (MDL)","MIDNAPORE (MDN)","MODINAGAR (MDNR)","MADHUPUR JN (MDP)","MADHOPUR PUNJAB (MDPB)","MADHIRA (MDR)","MANDASOR (MDS)","MADURAI JN (MDU)","MANDAVALLI (MDVL)","MARWAR MUNDWA (MDW)","MEDCHAL (MED)","VANCHIMANIYACHI (MEJ)","MAU AIMMA (MEM)","MAHIDPUR ROAD (MEP)","MALERKOTLA (MET)","MUKERIAN (MEX)","MUSAFIR KHANA (MFKA)","MISRAULI (MFL)","MUZAFFARPUR JN (MFP)","MORGRAM (MGAE)","MIGRENDISA (MGE)","MANDAGERE (MGF)","MANGLIYA GAON (MGG)","MANGOLPURI (MGLP)","MCCLUSKIEGANJ (MGME)","MEGHNAGAR (MGN)","MUGHAL SARAI JN (MGS)","MAILONGDISA (MGX)","MOHADI PRGN LNG (MHAD)","MHMDVD KHEDA RD (MHD)","MAGHAR (MHH)","MAHAJAN (MHJ)","MOHOPE (MHPE)","MAHUDA (MHQ)","MAHENDRAGARH (MHRG)","MANJHI (MHT)","MAHUVA JN (MHV)","MADHI (MID)","MIHRAWAN (MIH)","MILAK (MIL)","MIHINPURWA (MIN)","MIYANA (MINA)","MARWAR JN (MJ)","MEJA ROAD (MJA)","MAJBAT (MJBT)","MALKAJGIRI (MJF)","MAJHAGAWAN (MJG)","MAJHOWLIA (MJL)","MAKUM JN (MJN)","MAJRI JN (MJRI)","MANJESHWAR (MJS)","MAJHOLA PAKARYA (MJZ)","MIRANPUR KATRA (MK)","MOKAMEH JN (MKA)","MANKATHA (MKB)","MAKSI (MKC)","MAKUDI (MKDI)","MALAKHERA (MKH)","BAPUDM MOTIHARI (MKI)","MAKRANA JN (MKN)","MARKONA (MKO)","MANIKPUR JN (MKP)","MUKTAPUR (MKPR)","MADDIKERA (MKR)","MALLICKPUR HAT (MKRH)","MAKRONIA (MKRN)","MOKALSAR (MKSR)","MALKAPUR (MKU)","MORAK (MKX)","MALHOUR (ML)","MALANPUR (MLAR)","MODNIMB (MLB)","MALIHABAD (MLD)","MALDA TOWN (MLDT)","MALHARGARH (MLG)","MANDALGARH (MLGH)","MALIYA HATINA (MLHA)","MOHANLALGANJ (MLJ)","MELMARUVATTUR (MLMR)","MAILANI (MLN)","MALANCHA (MLNH)","MALUR (MLO)","MALLAPUR (MLP)","MALIPUR (MLPR)","MELATTUR (MLTR)","MALLARPUR (MLV)","MAULA ALI (MLY)","MALARNA (MLZ)","MUHAMMADABAD (MMA)","MAHMUDABAD AVDH (MMB)","MAHESHMUNDA (MMD)","MUL MARORA (MME)","MAHADANAPURAM (MMH)","MADURANTAKAM (MMK)","MADAN MAHAL (MML)","MANDAPAM (MMM)","MANMAD JN (MMR)","MANDASA ROAD (MMS)","MARWAR MATHANYA (MMY)","MANDAMARI (MMZ)","MANKAR (MNAE)","MUNDERWA (MND)","MANDI DHANAURA (MNDR)","MANSI JN (MNE)","MANDA ROAD (MNF)","MUNIGUDA (MNGD)","MANGAON (MNI)","MANOHARGANJ (MNJ)","MANAMADURAI JN (MNM)","MEHNAR ROAD (MNO)","MANANPUR (MNP)","MAINPURI (MNQ)","MANAKSAR (MNSR)","MULANTURUTTI (MNTT)","MUNGAOLI (MNV)","MOHOL (MO)","MONDH (MOF)","MOHIUDDINNAGAR (MOG)","MOGA (MOGA)","MORI BERA (MOI)","MULI ROAD (MOL)","MAMAN (MOM)","MODRAN (MON)","MUDDANURU (MOO)","MOHITNAGAR (MOP)","MOR (MOR)","MALOUT (MOT)","MOTICHUR (MOTC)","MOTH (MOTH)","MANOHARPUR (MOU)","MUZAFFARNAGAR (MOZ)","MANAPARAI (MPA)","MADANAPALLE RD (MPL)","MARTHIPALAYAM (MPLM)","MEDAPADU (MPU)","MURARPUR (MPY)","MANNARGUDI (MQ)","MUNROTURUTTU (MQO)","MALKHAID ROAD (MQR)","MALSIAN SHAHKHT (MQS)","MURUKKAMPUZHA (MQU)","MERALGRAM (MQX)","MORENA (MRA)","MUNIRABAD (MRB)","MURIBAHAL (MRBL)","MERAMANDOLIL (MRDL)","MURDESHWAR (MRDW)","MANAURI (MRE)","MARGHERITA (MRG)","MIRYALAGUDA (MRGA)","MORANHAT (MRHT)","MIRAJ JN (MRJ)","MARKAPUR ROAD (MRK)","MAROLI (MRL)","MORWANI (MRN)","MORINDA (MRND)","MAU RANIPUR (MRPR)","MURARAI (MRR)","MIRTHAL (MRTL)","CHENNAI EGMORE (MS)","MASUDAN (MSDN)","MAHESANA JN (MSH)","MAHES KHUNT (MSK)","MAHASAMUND (MSMD)","MASUR (MSR)","MASIT (MST)","MASKANWA (MSW)","MANSA (MSZ)","MEERUT CITY (MTC)","MERTA ROAD JN (MTD)","METUR DAM (MTDM)","MITHAPUR (MTHP)","MATHURA JN (MTJ)","MACHELIPATNAM (MTM)","METUPALAIYAM (MTP)","RAIMEHATPUR (MTPR)","MOTIPUR (MTR)","MATMARI (MTU)","MULTAI (MTY)","MURADNAGAR (MUD)","MUDKHED (MUE)","MANUGURU (MUGR)","MULKI (MULK)","MUPA (MUPA)","MANKAPUR JN (MUR)","MANDAWAR M RD (MURD)","MURI (MURI)","MEERUT CANT (MUT)","MANDUADIH (MUV)","MATHURAPUR (MUW)","MAYILADUTURAI J (MV)","MORBI (MVI)","MAVLI JN (MVJ)","MAVELIKARA (MVLK)","MILAVITTAN (MVN)","MANWATH ROAD (MVO)","MAIRWA (MW)","MALWAN (MWH)","MARWASGRAM (MWJ)","MORDAD TANDA (MWK)","MALLESWARAM (MWM)","MADWARANI (MWRN)","MARWAR LOHWAT (MWT)","MALLANWALA KHAS (MWX)","MARAUDA (MXA)","MAKHU (MXH)","MANDRAK (MXK)","MARIANI JN (MXN)","MAHUR (MXR)","MALAKPET KCG (MXT)","MANDYA (MYA)","MANDERDISA (MYD)","MIYAGAM KARJAN (MYG)","MAIHAR (MYR)","MYSORE JN (MYS)","MAYYANAD (MYY)","MIRZA CHEUKI (MZC)","MIRZAPALI (MZL)","MUZZAMPUR NRYN (MZM)","MIRZAPUR (MZP)","MURTAJAPUR (MZR)","MURKEONGSELEK (MZS)","NAGBHIR JN (NAB)","NAWA CITY (NAC)","NAGDA JN (NAD)","NAKSALBARI (NAK)","NAMRUP (NAM)","NANDGAON ROAD (NAN)","NANA (NANA)","NARANPUR (NANR)","NASRALA (NAS)","NARASINGAPALLI (NASP)","NATHNAGAR (NAT)","NEW AMRAVAT (NAVI)","NAWANDGI (NAW)","NAZIRGANJ (NAZJ)","NIMBHORA (NB)","NABHA (NBA)","NAJIBABAD JN (NBD)","NABENAGAR ROAD (NBG)","NIMBAHERA (NBH)","NADBAI (NBI)","NIMBAL (NBL)","NEW BONGAIGAON (NBQ)","NAMBURU (NBR)","NEW COOCH BEHAR (NCB)","NAGERCOIL JN (NCJ)","NAGORE (NCR)","NADIAD JN (ND)","NABADWIP DHAM (NDAE)","NANDURBAR (NDB)","NIDADAVOLU JN (NDD)","NANDGANJ (NDJ)","NADIKODE (NDKD)","NANDYAL (NDL)","NEW DELHI (NDLS)","NIDUBROLU (NDO)","NADAUJ (NDU)","NADWAN (NDW)","H SAHIB NANDED (NED)","NEORA (NEO)","NIVARI (NEW)","NEW FARAKKA JN (NFK)","NAGARI (NG)","NINGALA JN (NGA)","NAGAON (NGAN)","NAWABGANJ GONDA (NGB)","NAGINA (NGG)","NAGARI (NGI)","NANDGAON (NGN)","NEW GUNTUR (NGNT)","NAGAUR (NGO)","NAGPUR (NGP)","ANNIGERI (NGR)","NAGAPPATTINAM (NGT)","NAIHATI JN (NH)","NIHALGARH (NHH)","NAHARKATIYA (NHK)","NIGOHAN (NHN)","NALHATI JN (NHT)","JANJGIR NAILA (NIA)","NILAMBUR ROAD (NIL)","NIMTITA (NILE)","NIGAURA (NIQ)","NAINPUR JN (NIR)","NIRA (NIRA)","NABIPUR (NIU)","NEW JALPAIGURI (NJP)","NAGER COIL TOWN (NJT)","NASIK ROAD (NK)","NEKONDA (NKD)","NARKATIAGANJ JN (NKE)","NEW KATNI JN (NKJ)","NAMKON (NKM)","NIRAKARPUR (NKP)","NILAKANTHESWAR (NKW)","NALANDA (NLD)","NALGONDA (NLDA)","NANGAL DAM (NLDM)","NILESHWAR (NLE)","NAMLI (NLI)","NILOKHERI (NLKR)","NORTH LAKHIMPUR (NLP)","NELLORE (NLR)","NALBARI (NLV)","NUMALIGARH (NMGY)","NIMACH (NMH)","NIDAMANGALAM (NMJ)","NIM KA THANA (NMK)","NEW MISAMARI (NMM)","NAMTIALI (NMT)","NEW MAYNAGURI (NMX)","NEW MAL JN (NMZ)","NANDURA (NN)","NAUGACHIA (NNA)","NARANGI (NNGE)","NAYA NANGAL (NNGL)","NARNAUL (NNL)","NANGUNERI (NNN)","NANGLOI (NNO)","NANPARA JN (NNP)","NARAYANPUR (NNR)","NRYNPUR TATWAR (NNW)","NARIAOLI (NOI)","NOKHA (NOK)","NOAMUNDI (NOMD)","NEW ALIPURDAUR (NOQ)","NAWAPARA ROAD (NPD)","N. PANAKUDI (NPK)","NEPANAGAR (NPNR)","NAPASAR (NPS)","NIPHAD (NR)","NAGIREDDIPALLI (NRDP)","NANDALUR (NRE)","NERGUNDI (NRG)","NARANJIPUR (NRGR)","NARAINA (NRI)","NARKHER (NRKR)","NERAL (NRL)","NORLA ROAD (NRLR)","NURMAHAL (NRM)","NAKODAR JN (NRO)","NARSIPATNAM RD (NRP)","NARAYNPUR ANANT (NRPA)","NARAYANPET ROAD (NRPD)","NAGARUR (NRR)","NAGARIA SADAT (NRS)","NARASARAOPET (NRT)","NARWANA JN (NRW)","NOWROZABAD (NRZB)","NARASAPUR (NS)","NASIRABAD (NSD)","NAGARSOL (NSL)","NISUI (NSU)","NEW TINSUKIA JN (NTSK)","NAUTANWA (NTV)","NARSINGHPUR (NU)","NAVAGADH (NUD)","NUJELLA (NUJ)","NAGAR UNTARI (NUQ)","NARELA (NUR)","NAWAGAON (NVG)","NAVSARI (NVS)","NALWAR (NW)","NAGARWARA (NWA)","NIWAS ROAD (NWB)","NAWADAH (NWD)","NAUPADA JN (NWP)","NIWAR (NWR)","NAVAPUR (NWU)","NUAGAON (NXN)","NAYAGARH (NYG)","NAINI (NYN)","NAYAGAON (NYO)","NAYADUPETA (NYP)","NEYYATTINKARA (NYY)","NIZAMABAD (NZB)","NUZVID (NZD)","H NIZAMUDDIN (NZM)","NAZARETH (NZT)","OBRA DAM (OBR)","OBULAVARIPALLI (OBVP)","OBAIDULLA GANJ (ODG)","ONDAGRAM (ODM)","ODELA (OEA)","ONGOLE (OGL)","OKHLA (OKA)","OKHA (OKHA)","OMALUR (OML)","OLD MALDA (OMLF)","UNNAO JN (ON)","UPPAL (OPL)","ORAI (ORAI)","ORGA (ORGA)","OSIYAN (OSN)","OTTAPPALAM (OTP)","WARIA (OYR)","PARDI (PAD)","PAKALA JN (PAK)","PANAGARH (PAN)","PANDAVAPURA (PANP)","PANOLI (PAO)","PITHAPURAM (PAP)","PANDHURNA (PAR)","PARASHSHALA (PASA)","PURNA JN (PAU)","PEDANA (PAV)","PANDABESWAR (PAW)","PAYYANUR (PAY)","PAYANGADI (PAZ)","PUNTAMBA (PB)","PILIBHIT JN (PBE)","PARTAPGARH JN (PBH)","PMBAKVL SHANDY (PBKS)","PATHSALA (PBL)","PAMBAN JN (PBM)","PARBHANI JN (PBN)","PEMBARTI (PBP)","PORBANDAR (PBR)","PACHORA JN (PC)","PACHHAPUR (PCH)","PANCH PIPILA (PCN)","PALAKKODU (PCV)","POCHARAM (PCZ)","PADUBIDRI (PDD)","PINDRAI (PDE)","PADADHARI (PDH)","PEDAKAKANI HALT (PDKN)","PUDUKKOTTAI (PDKT)","PENDEKALLU (PDL)","PEDDAPALLI (PDPL)","PAYAGPUR (PDR)","PINDRA ROAD (PDRD)","PONDURU (PDU)","PANDAUL (PDW)","PUDUCHERRY (PDY)","PENCHARTHAL (PEC)","PATHARDIH JN (PEH)","PERALAM JN (PEM)","PHEPHNA JN (PEP)","PERAMBUR (PER)","PERNEM (PERN)","PHESAR (PES)","PHAPHAMAU JN (PFM)","PACHOR ROAD (PFR)","PARPANANGADI (PGI)","PILI BANGAN (PGK)","PUGALUR (PGR)","PIDUGURALLA (PGRL)","PALAKKAD (PGT)","PALGHAT TOWN (PGTN)","PHAGWARA JN (PGW)","PATHARIA (PHA)","PHAPHUND (PHD)","PUNARAKH (PHK)","POKHRAYAN (PHN)","PHILLAUR JN (PHR)","PIPRAIGAON (PIA)","PILER (PIL)","PIPLIA (PIP)","PENUKONDA (PKD)","POKLA (PKF)","PALAKOLLU (PKO)","PATTIKKAD (PKQ)","PAKUR (PKR)","PANSKURA (PKU)","PILKHUA (PKW)","PHALODI JN (PLCJ)","PALGHAR (PLG)","PETTAIVAYATALAI (PLI)","PALEJ (PLJ)","PHULWARTANR (PLJE)","PALIA KALAN (PLK)","PILAMEDU (PLMD)","PULGAON JN (PLO)","PHULPUR (PLP)","PIPALSANA (PLS)","PLASSEY (PLY)","PALAM (PM)","PARAMAKKUDI (PMK)","PIMPALKHUTI (PMKT)","PAPANASAM (PML)","PAMAN (PMN)","PIMPRI (PMP)","PITAMBARPUR (PMR)","PULLAMPET (PMT)","PARMANANDPUR (PMU)","PALI MARWAR (PMY)","PATNA JN (PNBE)","PATNA SAHEB (PNC)","PENDRA ROAD (PND)","PENNADAM (PNDM)","PRANTIK (PNE)","PANGAON (PNF)","PANCHGRAM (PNGM)","PANKI (PNK)","PARASNATH (PNME)","PANIPAT JN (PNP)","PUNKUNNAM (PNQ)","PUNSIA (PNSA)","PALANPUR JN (PNU)","PANVEL (PNVL)","PUNDHAG (PNW)","PANIAHWA (PNYA)","POKRAN (POK)","POTHIA (POT)","POTUL (POZ)","PURANPUR (PP)","PIPRAICH (PPC)","PIPLOD JN (PPD)","PIPARIYA (PPI)","PUNPUN (PPN)","PANPOSH (PPO)","PIPAR ROAD JN (PPR)","PIRPAINTI (PPT)","PEDDEMPET (PPZ)","PAWAPURI ROAD (PQE)","PINDLAI (PQL)","PARIAWAN K.K.RD (PQN)","PARBATI (PRB)","PARSIPUR (PRF)","PRAYAG (PRG)","POWERPET (PRH)","PATHRI (PRI)","POLUR (PRL)","PARLI VAIJNATH (PRLI)","PURNIA JN (PRNA)","PORJANPUR (PRNR)","PAHARPUR (PRP)","PURULIA JN (PRR)","PANRUTI (PRT)","PARAS (PS)","PALASA (PSA)","PARSABAD (PSB)","PARSODA (PSD)","PASRAHA (PSR)","PATIALA (PTA)","PATTAMBI (PTB)","PATRANGA (PTH)","PODANUR JN (PTJ)","PATHANKOT (PTK)","PATHARKANDI (PTKD)","POTKAPALLI (PTKP)","PATAUDI ROAD (PTRD)","PATARA (PTRE)","PATRATU (PTRU)","PARTUR (PTU)","PUDUKAD (PUK)","RAMPURA PHUL (PUL)","PUNDI (PUN)","PUNE JN (PUNE)","PURI (PURI)","PHUSRO (PUS)","PUTTUR (PUT)","PARASIA (PUX)","PEDDAVADIAPUDI (PVD)","PARVATIPURAM (PVP)","PARVATIPURAM TN (PVPT)","PANDHARPUR (PVR)","PIRAVAM ROAD (PVRD)","PARAVUR (PVU)","PALWAL (PWL)","PHULWARI SHARIF (PWS)","PALLIYADI (PYD)","PAYYOLI (PYOL)","QUILANDI (QLD)","KULEM (QLM)","KOLLAM JN (QLN)","KILA RAIPUR (QRP)","KANSRAO (QSR)","RAIPUR JN (R)","BARARA (RAA)","RAIGIR (RAG)","RAIRAKHOL (RAIR)","RAJAPUR ROAD (RAJP)","RANI (RANI)","RAY (RAY)","RAMBHA (RBA)","RAHIMABAD (RBD)","RAYBAG (RBG)","ROBERTS GANJ (RBGJ)","REOTI B KHERA (RBK)","RAE BARELI JN (RBL)","RUPBAS (RBS)","RAMBHADDARPUR (RBZ)","RAICHUR (RC)","RATHDHANA (RDDE)","RADHANPUR (RDHP)","RUDAULI (RDL)","RAMGUNDAM (RDM)","RADHIKAPUR (RDP)","RAMDEVRA (RDRA)","RAMPUR DUMRA (RDUM)","REWARI (RE)","RECHNI ROAD (RECH)","RITHI (REI)","REN (REN)","REWA (REWA)","RAFIGANJ (RFJ)","RAJGHAT NARORA (RG)","RAJGIR (RGD)","RAYAGADA (RGDA)","RAMGARHWA (RGH)","RAIGANJ (RGJ)","RENGALI (RGL)","ROTEGAON (RGO)","RAGHUNATHPALLI (RGP)","RAGHAVAPURAM (RGPM)","RINGAS JN (RGS)","RAGAUL (RGU)","RANAGHAT JN (RHA)","RAKHA MINES (RHE)","RAJGARH (RHG)","ROSHANPUR (RHN)","RAIGARH (RIG)","RAJANAGAR (RJA)","RAJGRAM (RJG)","RAJA KA SAHASPR (RJK)","RAJ NANDGAON (RJN)","RAZAMPETA (RJP)","RJNDR NGR BIHAR (RJPB)","RAJAPALAYAM (RJPM)","RAJALDESAR (RJR)","RAJKOT JN (RJT)","RAJAMUNDRY (RJY)","ROORKEE (RK)","RAIKA BAGH (RKB)","RUKADI (RKD)","RAJA KI MANDI (RKM)","RISHIKESH (RKSH)","RAJKHARSAWAN JN (RKSN)","RAJULA JN (RLA)","RAYALCHERUVU (RLO)","RAJMANE (RM)","RAMGANJ MANDI (RMA)","RAM CHAURA ROAD (RMC)","RAMANATHAPURAM (RMD)","RAMNA (RMF)","RAMANAGARAM (RMGM)","RAM NAGAR J K (RMJK)","RAMESWARAM (RMM)","RAMAN (RMN)","RAMANNAPET (RMNP)","RAHIMATPUR (RMP)","RAMPUR BAZAR (RMPB)","RAMNAGAR (RMR)","RAMNAGAR BENGAL (RMRB)","RAMGARH CANT (RMT)","RAMPUR (RMU)","RATNAGIRI (RN)","RANCHI (RNC)","RANIGANJ (RNG)","RANGALITING (RNGG)","RUNKHERA (RNH)","RANOLI (RNO)","RUPNARAYANPUR (RNPR)","RENUKUT (RNQ)","RANIBENNUR (RNR)","RANIWARA (RNV)","RANGIYA JN (RNY)","RUSERA GHAT (ROA)","ROHA (ROHA)","REOTI (ROI)","ROHTAK JN (ROK)","RUPSA JN (ROP)","ROURKELA (ROU)","ROZA JN (ROZA)","RANGAPARA NORTH (RPAN)","RUPNAGAR (RPAR)","RUPAUND (RPD)","RAMPUR HAT (RPH)","RAJPURA JN (RPJ)","RAGHUNATHPUR (RPR)","RUPRA ROAD (RPRD)","RATANPUR (RPUR)","RANAPRATAPNAGAR (RPZ)","RNINGR JLPAIGRI (RQJ)","BIRUR JN (RRB)","RANCHI ROAD (RRME)","RAGHURAJ SINGH (RRS)","RISIA (RS)","RISAMA (RSA)","RAISI (RSI)","RASRA (RSR)","RUTHIYAI (RTA)","RATANGARH JN (RTGH)","RAOTI (RTI)","RATLAM JN (RTM)","RATANPURA (RTP)","RENIGUNTA JN (RU)","RASULABAD (RUB)","RAULI (RUL)","RUPAMAU (RUM)","RUDRAPUR CITY (RUPC)","RANPUR (RUR)","RURA (RURA)","RAVER (RV)","RAVINDRAKHANI (RVKH)","ROWRIAH SDG (RWH)","RAIWALA (RWL)","RANAVAV (RWO)","ROWTA BAGAN (RWTB)","RAXAUL JN (RXL)","RAYANAPAD (RYP)","RASURIYA (RYS)","SHRIRANGAPATNA (S)","SALEM JN (SA)","SATHIAON (SAA)","SANICHARA (SAC)","SONADA (SAD)","SIMARIA (SAE)","SANGRUR (SAG)","SHRIRAJNAGAR (SAGR)","SAPHALE (SAH)","SARAI (SAI)","SALAR (SALE)","SANDILA (SAN)","SARDARNAGAR (SANR)","SATTENAPALLE (SAP)","SAHIBZADA ASNGR (SASN)","SANT ROAD (SAT)","SANAND (SAU)","SAVDA (SAV)","SURIAWAN (SAW)","SAHIBABAD (SBB)","SBB JOGULAMBA H (SBBJ)","BANGALORE CY JN (SBC)","SLEEMANABAD RD (SBD)","SORBHOG JN (SBE)","SAHIBGANJ JN (SBG)","SUBRAHMANYA RD (SBHR)","SABARMATI JN (SBI)","SHRIBDRYA LATHI (SBLT)","SONBARSA KCHERI (SBM)","SABAUR (SBO)","SAMBALPUR (SBP)","SAMBALPUR ROAD (SBPD)","SAMBALPUR CITY (SBPY)","SAMBHAR LAKE (SBR)","SABARMATI JN (SBT)","S BHAKHTIYARPUR (SBV)","SISWA BAZAR (SBZ)","SECUNDERABAD JN (SC)","SITAPUR CANT (SCC)","SENCHOA JN (SCE)","SACHIN (SCH)","SANCHI (SCI)","SALICHAUKA ROAD (SCKR)","SILCHAR (SCL)","SIMHACHALAM (SCM)","SHAM CHAURASI (SCQ)","SENGOTTAI (SCT)","SEALDAH (SDAH)","SHAHABAD (SDB)","SINDRIBLOCK HUT (SDBH)","SADISOPUR (SDE)","SUDSAR (SDF)","SRI DUNGARGARH (SDGH)","SARDARGRAM (SDGM)","SAGARDIGHI (SDI)","SHAHDOL (SDL)","SADULPUR JN (SDLP)","SUDAMDIH (SDMD)","SHOLAVANDAN (SDN)","SEYDUNGANALLUR (SDNR)","SADAT (SDT)","SON NAGAR (SEB)","SHEDBAL (SED)","SONPUR JN (SEE)","SHEGAON (SEG)","SEVAGRAM (SEGM)","SEHORE (SEH)","SELU (SELU)","SERAM (SEM)","SEOHARA (SEO)","SENDRA (SEU)","SAINTALA (SFC)","SUBEDARGANJ (SFG)","SAFEDABAD (SFH)","SUNAM (SFM)","SARANGPUR (SFW)","SHAJAPUR (SFY)","SAREIGRAM (SGAM)","SURGAON BANJARI (SGBJ)","SONGADH (SGD)","SIGADAM (SGDM)","SAGADAPATA (SGDP)","SANKARIDURG (SGE)","SANGAT (SGF)","SULTANGANJ (SGG)","SAFDARGANJ (SGJ)","SAGAULI JN (SGL)","SANGOLA (SGLA)","SHRI GANGANAGAR (SGNR)","SAUGOR (SGO)","SOHAGPUR (SGP)","SANGMESHWAR (SGR)","SANGARIA (SGRA)","SINGRAULI (SGRL)","SINGARAM (SGRM)","SHOGHI (SGS)","SILIGURI JN (SGUJ)","SHAMGARH (SGZ)","SAHARSA JN (SHC)","SHAHBAD MARKNDA (SHDM)","SEORAPHULI (SHE)","SHIRUD (SHF)","SHAHGANJ JN (SHG)","SHEIKPURA (SHK)","SHALIMAR (SHM)","SHIVNAGAR (SHNG)","SHADNAGAR (SHNR)","SIHORA ROAD (SHR)","SAHARSRAKUND (SHSK)","SILGHAT TOWN (SHTT)","SHOLINGHUR (SHU)","SUMMER HILL (SHZ)","SONALLI (SI)","SIDDHPUR (SID)","SIHO (SIHO)","SAKHI GOPAL (SIL)","SILAO (SILO)","SINI JN (SINI)","SAMAKHIALI B G (SIOB)","SURAIMANPUR (SIP)","SIHAPAR (SIPR)","SARKONI (SIQ)","SIRHIND JN (SIR)","SHIRRAVDE (SIW)","SANJAN (SJN)","SUJANPUR (SJNP)","SHUJALPUR (SJP)","SHUJAATPUR (SJT)","SIKANDRA RAO (SKA)","SHIKOHABAD JN (SKB)","SAKTESGARH (SKGH)","SAKRI JN (SKI)","SAHIBPUR KML JN (SKJ)","SAKLESHPUR (SKLR)","SINGARAYAKONDA (SKM)","SRIKRISHN NAGAR (SKN)","SUKINDA ROAD (SKND)","SHANKARPALLI (SKP)","SIKARPAI (SKPI)","SAKHPUR (SKR)","SALEKASA (SKS)","SAKTI (SKT)","SHAKTI NAGAR (SKTN)","SHIKARA (SKY)","SIRPUR KAGAZNGR (SKZR)","SURATHKAL (SL)","SALBONI (SLB)","SAKALDIHA (SLD)","SILLI (SLF)","SIMALUGURI JN (SLGR)","SANGLI (SLI)","SAKRIGALI JN (SLJ)","SALKAROAD (SLKR)","SULTANPUR (SLN)","SALAUNA (SLNA)","SAMALKOT JN (SLO)","SALOGRA (SLR)","SILAUT (SLT)","SOHWAL (SLW)","SAMALPATTI (SLY)","SAMSI (SM)","SHRI MAHABIRJI (SMBJ)","SIMBHOOLI (SMBL)","SAMBA (SMBX)","SAMNAPUR (SMC)","SHIMOGA (SME)","SHIMOGA TOWN (SMET)","SITAMARHI (SMI)","SAMALKHA (SMK)","SIMLA (SML)","SAMLAYA JN (SMLA)","SOMNATH (SMNH)","SEMAPUR (SMO)","SHYAMPURI (SMPA)","SHRI MADHOPUR (SMPR)","SHAMLI (SMQL)","SAMDHARI JN (SMR)","SARAI MIR (SMZ)","SNARAYAN CHAPIA (SNC)","SINDHUDURG (SNDD)","SANAT NAGAR (SNF)","SINGHPUR (SNGP)","SINDI (SNI)","SINDKHEDA (SNK)","SANKARANKOVIL (SNKL)","SANAHWAL (SNL)","SANTALPUR (SNLR)","SONEGAON (SNN)","SONIPAT (SNP)","SANKARPUR (SNQ)","SANSARPUR (SNRR)","SAINAGAR SHIRDI (SNSI)","SAINTHIA (SNT)","SANTALDIH (SNTD)","SONDAD (SNV)","SANEH ROAD (SNX)","SANOSRA (SOA)","SOJAT ROAD (SOD)","SURATGARH JN (SOG)","SIROHI ROAD (SOH)","SIHOR GUJARAT (SOJN)","SOLAN (SOL)","SONI (SONI)","SHIUPUR (SOP)","SONAGIR (SOR)","SORO (SORO)","SOMESAR (SOS)","SUHSARAI (SOW)","SITAPUR CITY (SPC)","SULLURUPETA (SPE)","SAMASTIPUR JN (SPJ)","SAPEKHATI (SPK)","SHAHJEHANPUR (SPN)","SHAHPUR PATOREE (SPP)","SINGAPURAM ROAD (SPRD)","SOMPETA (SPT)","SILAPATHAR (SPTR)","SAPATGRAM (SPX)","SAMPLA (SPZ)","SUKRITIPUR (SQF)","SONTALAI (SQL)","SARAI KANSRAI (SQN)","SULTANPUR LODI (SQR)","SARAGBUNDIA (SRBA)","SANTRAGACHI JN (SRC)","SAHARANPUR (SRE)","SAGAR JAMBAGARU (SRF)","SRIRANGAM (SRGM)","SURENDRANAGAR G (SRGT)","SALMARI (SRI)","SHRIDHAM (SRID)","SHANKARGARH (SRJ)","SORON (SRNK)","SRIRAMNAGAR (SRNR)","SARNATH (SRNT)","SIRATHU (SRO)","SERAMPORE (SRP)","SWARUPGANJ (SRPJ)","SHORANUR JN (SRR)","SATUR (SRT)","SHERTALAI (SRTL)","SIBSAGAR TOWN (SRTN)","SALEMPUR JN (SRU)","SIRPUR TOWN (SRUR)","SIRARI (SRY)","SIRSA (SSA)","SHAKURBASTI (SSB)","SUISA (SSIA)","SIRSAUL (SSL)","SASARAM (SSM)","SAI P NILAYAM (SSPN)","SARERI (SSR)","SURAT (ST)","SATNA (STA)","SITABINJ (STBJ)","SATHAJAGAT (STJT)","SASTHANKOTTA (STKT)","SIMULTALA (STL)","SITALPUR (STLR)","SITARAMPUR (STN)","SITAPUR (STP)","SITAFAL MANDI (STPD)","SATARA (STR)","SAHATWAR (STW)","SARDIHA (SUA)","SUDHANI (SUD)","SUJANGARH (SUJH)","SURENDRANAGAR (SUNR)","SOLAPUR JN (SUR)","SIURI (SURI)","SIWAN JN (SV)","SUWASRA (SVA)","SIVAGANGA (SVGA)","SISVINHALLI (SVHE)","SHIVAJINAGAR (SVJR)","SAVARKUNDLA (SVKD)","SIVAKASI (SVKS)","SANVERDAM CHUCH (SVM)","SHIVPURI (SVPI)","SRIVILLIPUTTUR (SVPR)","SHIVANARAYANPUR (SVRP)","SRIVAIKUNTAM (SVV)","SAVARDA (SVX)","SAHJANWA (SWA)","SHIVRAMPUR (SWC)","SIWAITH (SWE)","SAWAI MADHOPUR (SWM)","SEWAPURI (SWPR)","SONUA (SWR)","SAWANTWADI ROAD (SWV)","SALEM TOWN (SXT)","SIRKAZHI (SY)","SALAIA (SYA)","SARAI CHANDI (SYC)","SAIDRAJA (SYJ)","SAYAN (SYN)","SAIYID SARAWAN (SYWN)","SUBZI MANDI (SZM)","SARUPATHAR (SZR)","TANUR (TA)","TADALI (TAE)","TARANA ROAD (TAN)","TAPA (TAPA)","TATANAGAR JN (TATA)","TARGAON (TAZ)","TATIBAHAR (TBH)","TAMBARAM (TBM)","TIMARNI (TBN)","TAIABPUR (TBR)","TALBAHAT (TBT)","TIRUCHENDUR (TCN)","THRISUR (TCR)","TADEPALLIGUDEM (TDD)","TUNDLA JN (TDL)","TIRUPARANKNDRM (TDN)","TANDA URMAR (TDO)","TODARPUR (TDP)","TIRUPADRIPULYUR (TDPR)","TANDUR (TDU)","TAREGNA (TEA)","TENALI JN (TEL)","TELO (TELO)","TIRUNELVELI (TEN)","TETULMARI (TET)","TELTA (TETA)","TEGHRA (TGA)","TALEGAON (TGN)","TULJAPUR (TGP)","TENGANMADA (TGQ)","TANGIRIAPAL (TGRL)","TARIGOPPULA (TGU)","TEHTA (THA)","THAN JN (THAN)","THANA BIHPUR JN (THB)","THANDLA RD (THDR)","THURIA (THUR)","THERUBALI (THV)","THIVIM (THVM)","TILAYA (TIA)","TITLAGARH (TIG)","TIHU (TIHU)","TIRUR (TIR)","TATISILWAI (TIS)","TILARU (TIU)","TIVARI (TIW)","THANJAVUR (TJ)","TUMKUR (TK)","TUGLAKABAD (TKD)","TARIKERE JN (TKE)","THAKURGANJ (TKG)","THAKURTOTA (TKH)","TILAK BRIDGE (TKJ)","TANKUPPA (TKN)","TRIKARPUR (TKQ)","TAKARI (TKR)","TIKIRI (TKRI)","TILONIYA (TL)","TILDA (TLD)","TALGUPPA (TLGP)","TILHAR (TLH)","TALCHER ROAD (TLHD)","TALCHER (TLHR)","TALJHARI (TLJ)","TALAKHAJURI (TLKH)","TELIAMURA (TLMR)","TARLUPADU (TLU)","TALVADYA (TLV)","THALWARA (TLWA)","THALASSERY (TLY)","TUTI MELUR (TME)","TOMKA (TMKA)","TIRUMANGALAM (TMQ)","TUMSAR ROAD (TMR)","TINDIVANAM (TMV)","TIMMAPUR (TMX)","TAMLUK (TMZ)","TUTICORIN (TN)","THANE (TNA)","TORANAGALLU (TNGL)","TANUKU (TNKU)","TANGLA (TNL)","TIRUVANNAMALAI (TNM)","TANGUTURU (TNR)","TORI (TORI)","TIRCHRPALI FORT (TP)","TARAPITH ROAD (TPF)","TINPAHAR JN (TPH)","TIRUCHCHIRAPALI (TPJ)","TIRUPATTUR JN (TPT)","TIRUCHRPALI TWN (TPTN)","TIRUPATI (TPTY)","TANAKPUR (TPU)","TAPRI (TPZ)","TAKIA (TQA)","TELAM (TQM)","TIKUNIA (TQN)","TARU (TR)","TORANG (TRAN)","TIRUVERUMBUR (TRB)","TIRUKOILUR (TRK)","TIRUVALLUR (TRL)","TIRORA (TRO)","TARAORI (TRR)","TARSARAI (TRS)","TIRUTTANI (TRT)","TRIUPUNITTURA (TRTR)","TIRUVALLA (TRVL)","TISUA (TSA)","TAHSIL FATEHPUR (TSF)","TENKASI JN (TSI)","TINSUKIA JN (TSK)","TSUNDURU (TSR)","TITABAR (TTB)","TIRUTTANGAL (TTL)","TIPTUR (TTR)","TADIPATRI (TU)","TIRUNNAVAYA (TUA)","TIRALDIH (TUL)","TOHANA (TUN)","TUNG (TUNG)","TUNI (TUNI)","TIRUPPUR (TUP)","TUVVUR (TUV)","TURAVUR (TUVR)","TRIVANDRUM CNTL (TVC)","TARADEVI (TVI)","TADWAL (TVL)","TRIVANDRUM PETT (TVP)","THIRUVARUR JN (TVR)","TALWANDI (TWB)","TWINING GANJ (TWG)","UPLETA (UA)","UPPALA (UAA)","AMBALA CITY (UBC)","HUBLI JN (UBL)","UMBARGAM ROAD (UBR)","UCHANA (UCA)","UNCHAHAR JN (UCR)","UDUPI (UD)","UDGIR (UDGR)","ANDAL JN (UDL)","UNDASA MADHAWPU (UDM)","UDHNA JN (UDN)","AMDARA (UDR)","UDAIPUR CITY (UDZ)","UGAR KHURD (UGR)","UNA HIMACHAL (UHL)","UDHAMPUR (UHP)","UNCHHERA (UHR)","UJALVAV (UJ)","UNJHA (UJA)","UJHANI (UJH)","UJJAIN JN (UJN)","UJIARPUR (UJP)","UKHRA (UKA)","UTTUKULI (UKL)","ULUBARIA (ULB)","ACHALDA (ULD)","UDALGURI (ULG)","ULLAL (ULL)","KULTI (ULT)","AMBALA CANT JN (UMB)","USMANABAD (UMD)","UMARIA (UMR)","UMRI (UMRI)","UMDANAGAR (UR)","UNTARE ROAD (URD)","UREN (UREN)","URGA (URGA)","URULI (URI)","UNJALUR (URL)","UGRASENPUR (URPR)","USALAPUR (USL)","UMAR TALI (UTA)","UTARLAI (UTL)","UTRAHTIA (UTR)","UDVADA (UVD)","BHAGA JN (VAA)","VARKALA (VAK)","VAPI (VAPI)","VALAPATTANAM (VAPM)","VAIKOM (VARD)","BOBBILI (VBL)","VAIBHAVWADI RD (VBW)","VASAD JN (VDA)","VENDODU (VDD)","VEDAYAPALEM (VDE)","VITHISVARANKOL (VDL)","VIDYASAGAR (VDS)","VEER (VEER)","VIRAMGAM JN (VG)","VALAPPADI G HLT (VGE)","VANGAON (VGN)","WIHIRGAON (VHGN)","VILAVADE (VID)","VIJAY PUR (VJP)","VIJIYPUR JAMMU (VJPJ)","VERKA JN (VKA)","VIKARABAD JN (VKB)","VENKATAGIRI (VKI)","VINUKONDA (VKN)","VENKATNAGRA (VKR)","VALLIKUNNU (VLI)","VELLANKANNI (VLNK)","VELLORE CANT (VLR)","VALLIYUR (VLY)","VILLUPARAM JN (VM)","VIKRAMGARH ALOT (VMA)","VADLAMANNADU (VMD)","VANIYAMBADI (VN)","VARANGAON (VNA)","VANIYAMBALAM (VNB)","VISWANATH CHRLI (VNE)","VISHNUPURAM (VNUP)","VIDYAPATINAGAR (VPN)","BHUPIA MAU (VPO)","VIRUDUNAGAR JN (VPT)","VAILAPUZHA (VPZ)","VIRAR (VR)","VISHRAMBAG (VRB)","VIKRAMNAGAR (VRG)","VIRBHADRA (VRH)","VRIDHACHALAM JN (VRI)","VERAVAL (VRL)","VIRPUR (VRR)","VISHVAMITRI (VS)","VASCO DA GAMA (VSG)","VISHAKAPATNAM (VSKP)","BIJAYSOTA (VST)","BISHNUPUR (VSU)","VARTEJ (VTJ)","VETAPALEMU (VTM)","VALIVADE (VV)","VIVEKA VIHAR (VVB)","VIRAVASARAM (VVM)","VYARA (VYA)","VYASNAGAR (VYN)","VIZIANAGRAM JN (VZM)","WADI (WADI)","WANI (WANI)","WADHWAN CITY (WC)","WADRENGDISA (WDA)","WYNDHAMGANJ (WDM)","WADIARAM (WDR)","WENA (WENA)","WHITEFIELD (WFD)","WASHIM (WHM)","WIRUR (WIRR)","WALAJAH ROAD JN (WJR)","WADAKANCHERI (WKI)","WANKANER JN (WKR)","WARANGAL (WL)","WANPARTI ROAD (WPR)","WARDHA JN (WR)","WARORA (WRR)","WARIS ALEGANJ (WRS)","WADSA (WSA)","WANSJALIYA (WSJ)","JAM WANTHALI (WTJ)","WATHAR (WTR)","WAZERGANJ (WZJ)","YERRAGUNTLA (YA)","YUSUFPUR (YFP)","YADGIR (YG)","YEOLA (YL)","YALVIGI (YLG)","ELLAMANCHILI (YLM)","YELHANKA JN (YNK)","ERRUPALEM (YP)","YESVANTPUR JN (YPR)","ZAHIRABAD (ZB)","ZAFARABAD JN (ZBD)","JANGAON (ZN)","ZAMANIA (ZNA)","JIRADEI (ZRDE)","ZAWAR (ZW)"];
	$('#sourcestationsearchtrain').autocomplete({
	  source: stationname
	});
	$('#deststationsearchtrain').autocomplete({
	  source: stationname
	});

	//Trains between two stations - Finding results
	function trainBetweenStations(){
		//Search Train check whether date is greater than or equal to today
		$('#displaytrainfareavailability').hide();
		var screenWidth = $(window).width();
		var givenDay = $('#searchtraindateday').val();
		var givenMon = $('#searchtraindatemon').val();
		var givenYear = $('#searchtraindateyear').val();
		var givenDateOrg = givenYear+'-'+givenMon+'-'+givenDay;
		var today = new Date();
		todayTime = today.getTime();
		givenDate = new Date(givenDateOrg);
		givenTime = givenDate.getTime();

		var src_stn = $('#sourcestationsearchtrain').val();
		if(src_stn){}else{alert("Enter a Valid Source");return false;}
		src_stn = src_stn.match(/\(([^()]+)\)$/)[1];

		var dest_stn = $('#deststationsearchtrain').val();
		if(dest_stn){}else{alert("Enter a Valid Destination");return false;}
		dest_stn = dest_stn.match(/\(([^()]+)\)$/)[1];

		if(givenTime-todayTime>-86400000){}else{alert("Enter a date greater than or equal to today");return false;}

		$('#displaytrainbetweenstations').html("<h5><i class=\"icon-refresh icon-spin\"></i> Retrieving the trains between two stations...</h5>").show();
		$.ajax({
			type: "POST",
			url: "../userscripts/searchtrainschedule.php",
			data: "src_stn="+src_stn+"&dest_stn="+dest_stn+"&sel_date="+givenDateOrg+"&screenWidth="+screenWidth ,
			success: function(html){
				$('#displaytrainfareavailability').hide();
				$('#displaytrainbetweenstations').html(html);
				dataLayer.push({'event': 'searchtrains_LOT'});
				//_gaq.push(['_trackEvent','Search Trains','List of Trains']);
			}
		});
	}
	$('#getsearchtrains').click(function(){ trainBetweenStations();});
	$('#searchtraindateday').pressEnter(function(){ trainBetweenStations();});
	$('#searchtraindatemon').pressEnter(function(){ trainBetweenStations();});
	$('#searchtraindateyear').pressEnter(function(){ trainBetweenStations();});
	var tempsrcstn1 = $('#sourcestationsearchtrain').val();
	$('#sourcestationsearchtrain').pressEnter(function(){ 
		var tempsrcstn2 = $('#sourcestationsearchtrain').val();
		if(tempsrcstn1==tempsrcstn2){
			trainBetweenStations();
		}
		tempsrcstn1 = $('#sourcestationsearchtrain').val();
	});
	var tempdeststn1 = $('#deststationsearchtrain').val();
	$('#deststationsearchtrain').pressEnter(function(){ 
		var tempdeststn2 = $('#deststationsearchtrain').val();
		if(tempdeststn1==tempdeststn2){
			trainBetweenStations();
		}
		tempdeststn1 = $('#deststationsearchtrain').val();
	});

	//Focus on text box on page landing
	$('input[name="irctcusername"]').focus(); //IRCTC Import Page
	$('#sourcestationsearchtrain').focus(); //Trains Page
	$('input[name="displaypnrstatusinput"]').focus() //PNR Status Page

	//Focus on inputs in Login, Register, Send SMS Modals
	$('#myLoginModal').on('shown', function () {
		$('#loginmobileNum').focus();
	});
	$('#myRegisterModal').on('shown', function () {
		$('#registermobileNum').focus();
	});
	$('#mySMSModal').on('shown', function () {
		$('#currentmobileNum').focus();
	});

	//PNR History - Active Archive tickets toggle
	// $('#activeticketslink').click(function(){
	// 	$('#activeticketslink').attr('class','active');
	// 	$('#archiveticketslink').attr('class','');
	// 	$('#pnrhistoryactivetickets').show();
	// 	$('#pnrhistoryarchivetickets').hide();
	// });
	// $('#archiveticketslink').click(function(){
	// 	$('#activeticketslink').attr('class','');
	// 	$('#archiveticketslink').attr('class','active');
	// 	$('#pnrhistoryactivetickets').hide();
	// 	$('#pnrhistoryarchivetickets').show();
	// });

	//AJAX Login
	function ajaxLogin(){
		var mobileNum = $('#loginmobileNum').val();
		var userPassword = $('#loginPassword').val();
		if(mobileNum){
			if(userPassword){
			}else{
				alert("Enter Password");
				return false;
			}
		}else{
			alert("Enter Username");
			return false;
		}
		$('#userLogin').html("<i class=\"icon-refresh icon-spin\"></i> Logging In...");
		$.ajax({
			type: "POST",
			url: "../user/loginaction.php",
			data: "mobileNum="+mobileNum+"&userPassword="+userPassword+"&userLogin=ajaxLogin",
			success: function(html){
				var result = html
				if(result=="wrong"){
					alert("Wrong Username or Password");
					$('#userLogin').html("Login");
					dataLayer.push({'event': 'login_failure'});
				}else{
					dataLayer.push({'event': 'login_success'});
					//_gaq.push(['_trackEvent','Login','Success']);
					window.location.href=html;
				}
			}
		});
	}
	$('#userLogin').click(function(){ ajaxLogin(); });
	var tempmobNum = $('#loginmobileNum').val();
	$('#loginmobileNum').pressEnter(function(){ 
		var tempmobNum2 = $('#loginmobileNum').val();	
		if(tempmobNum==tempmobNum2){
			ajaxLogin();
		}
		tempmobNum=$('#loginmobileNum').val();
	});
	$('#loginPassword').pressEnter(function(){ ajaxLogin(); });

	//Blurring mobile num change and password change alerts
	$(function() {
		setTimeout(function() {
			$("#changePasswordAlert").hide('blind', {}, 500);
			$("#changeMobileAlert").hide('blind', {}, 500);
		}, 5000);
	});

	//Check for Current time between 1130 PM and 1230 AM
	function currentTimeCheck(){
		var currentTime = new Date();
		currentTimeHour = currentTime.getHours();
		currentTimeMin = currentTime.getMinutes();
		if(currentTimeHour==0){
			if(currentTimeMin<=30){
				alert("Indian Railways Servers are down between 11.30 PM and 12.30 AM!");
				return false;
			}
		}
		if(currentTimeHour==23){
			if(currentTimeMin>=30){
				alert("Indian Railways Servers are down between 11.30 PM and 12.30 AM!");
				return false;
			}
		}
		return true;
	}

	//Sync with IRCTC - small sync now button
	function syncIrctcButton(irctcusername){
		$('#displayirctcimportbtnstatus').html("<h5><i class=\"icon-refresh icon-spin\"></i> Syncing PNR History of your IRCTC account...</h5>");
		//current.html("<i class=\"icon-refresh icon-spin\"></i> Importing...");
		$.ajax({
			type: "POST",
			url: "../userscripts/irctcpnrhistoryimport.php",
			data: "irctcUsername="+irctcusername+"&savePnrHistoryButton=Y" ,
			success: function(html){
				var result = html;
				if(result=="Success"){
					$('#displayirctcimportbtnstatus').html("<h5>Successfully Synced your booking history!</h5>");
					$(function() {
						setTimeout(function() {
							location.reload();
						}, 2000);
					});
					//current.html("<i class=\"icon-thumbs-up\"></i> Success");
				} else if(result=="Failure"){
					$('#displayirctcimportbtnstatus').html("<h5>Your Booking history has been synced and upto date!!</h5>");
					$(function() {
						setTimeout(function() {
							location.reload();
						}, 2000);
					});
					//current.html("<i class=\"icon-warning-sign\"></i> Enough");
				} else if(result=="WrongPassword"){
					$('#displayirctcimportbtnstatus').html("<h5>Wrong Username or Password! Please Try Again!</h5>");
				}else {
					$('#displayirctcimportbtnstatus').html("<h5>There is a problem connecting to IRCTC Servers. Please try again!</h5>");
					//current.html("<i class=\"icon-warning-sign\"></i> Try Again");
				} 			
			}
		});
	}

	$('.irctcsyncnowbtn').click(function(){ 
		var current = $(this);
		var irctcusername = current.attr('name');
		syncIrctcButton(irctcusername); 
	});

	$('.irctcremovebtn').click(function(){
		var current = $(this);
		var irctcusername = current.attr('name');
		$('#displayirctcimportbtnstatus').html("<h5><i class=\"icon-refresh icon-spin\"></i> Removing your IRCTC account...</h5>");
		$.ajax({
			type: "POST",
			url: "../userscripts/irctc-remove-account.php",
			data: "irctcUsername="+irctcusername+"&removeAccount=Y" ,
			success: function(html){
				var result = html;
				if(result=="Success"){
					$(function() {
						setTimeout(function() {
							location.reload();
						}, 1000);
					});
					//current.html("<i class=\"icon-thumbs-up\"></i> Success");
				} else {
					$('#displayirctcimportbtnstatus').html("<h5>There is a problem removing your account. Please try again!</h5>");
					//current.html("<i class=\"icon-warning-sign\"></i> Try Again");
				} 			
			}
		});

	});

	//search train auto tab
	$('#searchtraindateday, #searchtraindatemon, #searchtraindateyear').autotab_magic().autotab_filter('numeric');

	//search train - getting fare and availability
	$(document).on("click",'.trains2stations',function(){
		$('html, body').animate({
	        scrollTop: $("#displaytrainfareavailability").offset().top -100
	    }, 200);
		var current = $(this);
		var travelDetails = current.val();
		$('#displaytrainfareavailability').show();
		$('#displaytrainfareavailability').html("<h5><i class=\"icon-refresh icon-spin\"></i> Getting Fare and Availability Details...</h5>");
		$.ajax({
			type: "POST",
			url: "../userscripts/fare-availability.php",
			data: "travelDetails="+travelDetails+"&getSeatAvailability=Y" ,
			success: function(html){
				var result = html;
				$('#displaytrainfareavailability').html(result);
				$('html, body').animate({
			        scrollTop: $("#displaytrainfareavailability").offset().top -100
			    }, 1000);
			    dataLayer.push({'event': 'searchtrains_FSA'});
			    //_gaq.push(['_trackEvent','Search Trains','Fare Availability']);
			}
		});
	});

	//Linking 160by2 Account
	function onesixVA(){
		if($('#onesixVA').attr('class')=="btn btn-inverse disabled"){
			return false;
		}
		var onesixU = $('#onesixU').val();
		var onesixP = $('#onesixP').val();
		if(onesixU){
			if(onesixP){
			}else{
				alert("Enter Password");
				return false;
			}
		}else{
			alert("Enter Username");
			return false;
		}
		$('#onesixVA').html("<i class=\"icon-refresh icon-spin\"></i> Verifying..");
		$.ajax({
			type: "POST",
			url: "../userscripts/smsaccount-verify.php",
			data: "onesixU="+onesixU+"&onesixP="+onesixP ,
			success: function(html){
				if(html=="Success"){
					$('#onesixVA').html("<i class=\"icon-ok\"></i> Verified");
					$('#onesixVA').attr('class','btn btn-inverse disabled');
					dataLayer.push({'event': 'onesixtybytwo_accadd'});
					//_gaq.push(['_trackEvent','OneSixtyByTwo','Account Added']);
					window.location.href = "../user/profile";
				}
				if(html=="Failure"){
					alert("Wrong Username or Password! Please check and try again!");
					$('#onesixVA').html("Verify & Add");
					dataLayer.push({'event': 'onesixtybytwo_wrongacc'});
				}
			}
		});
	}
	$('#onesixVA').click(function(){ onesixVA(); });
	$('#onesixU').pressEnter(function(){ onesixVA(); });
	$('#onesixP').pressEnter(function(){ onesixVA(); });

	function checkLinkedAccount(){
		var linkedsmsAccount = $('#linkedsmsaccount').val();
		if(linkedsmsAccount==100){
			return true;
		}else{
			alert("You do not have a Free SMS Account linked to your profile! Please Link an account and try again!")
			return false;
		}
	}
});

//Disabling tooltip on smaller screens
if ($(window).width() < 760) {
   $('*').tooltip('disable');
   $('.desktoptrains2stations').hide();
   $('.mobiletrains2stations').show();
}

$(window).resize(function() {
  if ($(window).width() < 760) {
     $('*').tooltip('disable');
     $('.desktoptrains2stations').hide();
     $('.mobiletrains2stations').show();
  }else{
	 $('*').tooltip('enable');
	 $('.desktoptrains2stations').show();
     $('.mobiletrains2stations').hide();
  }
});